Rails.application.routes.draw do

=begin
 #new high score form
 get 'high_scores/new', to:'high_scores#new', as: 'new_high_score'

 #editing an existing HighScore object
 get 'high_scores/:id/edit', to: 'high_scores#edit', as: 'edit_high_score'

 #renders a single high_score
 get 'high_scores/:id', to:'high_scores#show', as:'high_score'

 #renders all high_scores in database
 get 'high_scores', to:'high_scores#index', as:'high_scores'

 #user is brought to this page for high_score object creation
 post 'high_scores', to:'high_scores#create'

 #after form generated by edit is filled out
 #user comes to this page to update the actual object
 patch 'high_scores/:id', to: 'high_scores#update'

 delete 'high_scores/:id', to: 'high_scores#destroy'
=end
 
 resources :high_scores

 root 'high_scores#index'

end
