# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

t = Time.now + 3

users = User.create(
  [
    { name: 'alice', password: 'a', firewall: 5, honeypot: 2, zeroday: 2 },    
    { name: 'bob', password: 'b', firewall: 2, honeypot: 2, active_firewall: 5, active_honeypot: 3 },    
    { name: 'charlie', password: 'c' },    
    { name: 'david', password: 'd' }    
  ]
)

breaches = Breach.create(
  [
    #alice is targeting bob OR bob is targeted by alice
    {user_id: 1, target_id: 2, breached: false},
    {user_id: 1, target_id: 3, breached: true, cash_stolen: 1000},
    {user_id: 1, target_id: 2, breached: false},

    {user_id: 2, target_id: 1, breached: false},
    {user_id: 2, target_id: 4, breached: false},

    {user_id: 3, target_id: 1, breached: false},

    {user_id: 4, target_id: 1, breached: false},
    {user_id: 4, target_id: 2, breached: false}
  ]
)

operatives = Operative.create(
  [
    { user_id: 1, name: 'Smiling Gibbon', status: 'deployed', skill: 7, job_id: 1 },
    { user_id: 1, name: 'Sitting Tofu', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Fuze', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Black Swan', status: 'mia', skill: 3, job_id: nil },

    { user_id: 2, name: 'Daft Adder', status: 'injured', skill: 6, job_id: nil },
    { user_id: 2, name: 'Stale Hammer', status: 'deployed', skill: 2, job_id: nil },
    { user_id: 2, name: 'Orange Rocket', status: 'deployed', skill: 3, job_id: nil },
    { user_id: 2, name: 'Steel Sun', status: 'deployed', skill: 4, job_id: nil },

    { user_id: 4, name: 'Yoga', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Cunning Turtle', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Gypsy', status: 'dead', skill: 4, job_id: nil },
    { user_id: 4, name: 'Alpha', status: 'mia', skill: 8, job_id: nil }

  ]
)


jobs = Job.create(
    [
name: 'smokescreen', payout: 306, reward: 'none', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 45, xp: 92 },
name: 'smokescreen', payout: 1966, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 30, xp: 342 },
name: 'gale', payout: 593, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 169, xp: 649 },
name: 'breach', payout: 1894, reward: 'firewall', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 77, xp: 940 },
name: 'muffintop', payout: 1193, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 37, xp: 292 },
name: 'anvil', payout: 738, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 64, xp: 940 },
name: 'hellraiser', payout: 1325, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 162, xp: 770 },
name: 'victor', payout: 498, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 82, xp: 539 },
name: 'little boy', payout: 1490, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 132, xp: 351 },
name: 'salamander', payout: 844, reward: 'none', difficulty: 11, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 173, xp: 0 },
name: 'richard', payout: 1754, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 139, xp: 540 },
name: 'blowback', payout: 1959, reward: 'firewall', difficulty: 8, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 163, xp: 688 },
name: 'turkey', payout: 1615, reward: 'none', difficulty: 8, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 145, xp: 104 },
name: 'jam out clam out', payout: 278, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 176, xp: 434 },
name: 'baboon', payout: 571, reward: 'none', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 96, xp: 550 },
name: 'moose', payout: 444, reward: 'none', difficulty: 9, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 32, xp: 828 },
name: 'second coming', payout: 1943, reward: 'honeypot', difficulty: 11, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 150, xp: 704 },
name: 'shutdown', payout: 1817, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 122, xp: 86 },
name: 'trump-inator', payout: 1732, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 136, xp: 110 },
name: 'smokescreen', payout: 1130, reward: 'none', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 95, xp: 126 },
name: 'hardball', payout: 1624, reward: 'o_contract', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 177, xp: 177 },
name: 'juicy', payout: 1477, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 158, xp: 275 },
name: 'black eye', payout: 167, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 66, xp: 370 },
name: 'thunder****', payout: 1999, reward: 'o_contract', difficulty: 12, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 100, xp: 660 },
name: 'goat cheese', payout: 1293, reward: 'none', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 180, xp: 390 },
name: 'chico', payout: 1042, reward: 'o_contract', difficulty: 4, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 177, xp: 28 },
name: 'shutdown', payout: 195, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 136, xp: 170 },
name: 'sherpa', payout: 1810, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 107, xp: 1164 },
name: 'f.o.b.', payout: 1297, reward: 'none', difficulty: 1, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 138, xp: 70 },
name: 'black eye', payout: 1699, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 78, xp: 308 },
name: 'second coming', payout: 154, reward: 'honeypot', difficulty: 6, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 159, xp: 510 },
name: 'muffintop', payout: 1316, reward: 'none', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 67, xp: 670 },
name: 'salamander', payout: 269, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 96, xp: 129 },
name: 'richard', payout: 945, reward: 'o_contract', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 96, xp: 531 },
name: 'black hawk', payout: 223, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 145, xp: 164 },
name: 'richard', payout: 1300, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 32, xp: 20 },
name: 'blacksmith', payout: 1109, reward: 'none', difficulty: 4, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 171, xp: 100 },
name: 'shutdown', payout: 1908, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 109, xp: 80 },
name: 'taco', payout: 230, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 32, xp: 150 },
name: 'moose', payout: 463, reward: 'o_contract', difficulty: 5, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 104, xp: 310 },
name: 'moose', payout: 1107, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 102, xp: 765 },
name: 'little boy', payout: 217, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 36, xp: 704 },
name: 'black eye', payout: 579, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 68, xp: 110 },
name: 'dustoff', payout: 1148, reward: 'none', difficulty: 10, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 162, xp: 950 },
name: 'moose', payout: 1765, reward: 'firewall', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 133, xp: 6 },
name: 'little boy', payout: 1211, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 145, xp: 225 },
name: 'blowback', payout: 1600, reward: 'o_contract', difficulty: 2, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 47, xp: 16 },
name: 'anvil', payout: 376, reward: 'o_contract', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 46, xp: 301 },
name: 'breach', payout: 1009, reward: 'honeypot', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 109, xp: 1008 },
name: 'top gun', payout: 60, reward: 'o_contract', difficulty: 3, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 108, xp: 30 },
name: 'brown nose', payout: 1804, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 157, xp: 200 },
name: 'hackathon', payout: 929, reward: 'firewall', difficulty: 9, description: 'Aid LEO search for subject.', time_to_complete: 136, xp: 90 },
name: 'smokescreen', payout: 1380, reward: 'o_contract', difficulty: 4, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 78, xp: 268 },
name: 'top gun', payout: 83, reward: 'honeypot', difficulty: 7, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 44, xp: 462 },
name: 'iron eagle', payout: 1054, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 174, xp: 747 },
name: 'hellraiser', payout: 816, reward: 'none', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 180, xp: 150 },
name: 'goat cheese', payout: 862, reward: 'none', difficulty: 1, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 49, xp: 58 },
name: 'false idol', payout: 441, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 143, xp: 31 },
name: 'jaba', payout: 1650, reward: 'firewall', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 92, xp: 87 },
name: 'hurricane', payout: 71, reward: 'none', difficulty: 5, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 94, xp: 490 },
name: 'turkey', payout: 138, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 84, xp: 253 },
name: 'cheney', payout: 883, reward: 'none', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 115, xp: 228 },
name: 'black hawk', payout: 827, reward: 'none', difficulty: 1, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 121, xp: 32 },
name: 'goat cheese', payout: 59, reward: 'firewall', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 33, xp: 240 },
name: 'false idol', payout: 1936, reward: 'firewall', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 133, xp: 306 },
name: 'brown nose', payout: 290, reward: 'none', difficulty: 5, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 53, xp: 105 },
name: 'recovery', payout: 524, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 120, xp: 138 },
name: 'salamander', payout: 597, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 170, xp: 40 },
name: 'firesail', payout: 1370, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 68, xp: 348 },
name: 'embedded', payout: 855, reward: 'firewall', difficulty: 9, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 69, xp: 180 },
name: 'iron eagle', payout: 738, reward: 'zero_day', difficulty: 9, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 101, xp: 297 },
name: 'embedded', payout: 1834, reward: 'firewall', difficulty: 11, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 135, xp: 154 },
name: 'anvil', payout: 583, reward: 'none', difficulty: 7, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 96, xp: 224 },
name: 'hackathon', payout: 220, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 78, xp: 561 },
name: 'tango', payout: 921, reward: 'o_contract', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 159, xp: 46 },
name: 'hellraiser', payout: 132, reward: 'none', difficulty: 7, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 154, xp: 651 },
name: 'backdraft', payout: 510, reward: 'none', difficulty: 4, description: 'Aid LEO search for subject.', time_to_complete: 132, xp: 76 },
name: 'goat cheese', payout: 91, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 119, xp: 637 },
name: 'fat man', payout: 656, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 98, xp: 0 },
name: 'tango', payout: 1645, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 127, xp: 141 },
name: 'muffintop', payout: 191, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 116, xp: 284 },
name: 'victor', payout: 115, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 150, xp: 259 },
name: 'f.o.b.', payout: 1882, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 37, xp: 234 },
name: 'thunder****', payout: 208, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 172, xp: 20 },
name: 'hell raiser', payout: 723, reward: 'o_contract', difficulty: 7, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 95, xp: 364 },
name: 'turtle', payout: 1918, reward: 'honeypot', difficulty: 7, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 162, xp: 63 },
name: 'gibbon', payout: 228, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 59, xp: 13 },
name: 'cheney', payout: 1742, reward: 'none', difficulty: 12, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 126, xp: 132 },
name: 'thunder****', payout: 889, reward: 'none', difficulty: 1, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 137, xp: 0 },
name: 'trump-inator', payout: 877, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 30, xp: 200 },
name: 'moose', payout: 1100, reward: 'honeypot', difficulty: 3, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 38, xp: 114 },
name: 'blowback', payout: 260, reward: 'none', difficulty: 2, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 63, xp: 26 },
name: 'turkey', payout: 1341, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 173, xp: 150 },
name: 'applesauce', payout: 251, reward: 'firewall', difficulty: 11, description: 'Aid LEO search for subject.', time_to_complete: 89, xp: 429 },
name: 'bluejay', payout: 780, reward: 'firewall', difficulty: 6, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 113, xp: 18 },
name: 'whateverthefuck', payout: 1268, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 168, xp: 440 },
name: 'bannana? bannanna?', payout: 1627, reward: 'firewall', difficulty: 9, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 68, xp: 891 },
name: 'hackathon', payout: 1573, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 87, xp: 450 },
name: 'hurricane', payout: 822, reward: 'o_contract', difficulty: 9, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 123, xp: 297 },
name: 'bern-inator', payout: 1140, reward: 'firewall', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 143, xp: 550 },
name: 'iron eagle', payout: 1823, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 130, xp: 232 },
name: 'fat man', payout: 1675, reward: 'none', difficulty: 1, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 128, xp: 44 },
name: 'little boy', payout: 1204, reward: 'none', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 153, xp: 814 },
name: 'taco', payout: 988, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 45, xp: 63 },
name: 'turtle', payout: 1513, reward: 'honeypot', difficulty: 12, description: 'Aid LEO search for subject.', time_to_complete: 178, xp: 672 },
name: 'victor', payout: 413, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 128, xp: 205 },
name: 'jam out clam out', payout: 12, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 78, xp: 249 },
name: 'muffintop', payout: 226, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 167, xp: 69 },
name: 'fang', payout: 213, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 172, xp: 846 },
name: 'embedded', payout: 1671, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 113, xp: 276 },
name: 'loose goose', payout: 146, reward: 'firewall', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 160, xp: 92 },
name: 'juicy', payout: 1101, reward: 'firewall', difficulty: 8, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 158, xp: 744 },
name: 'black hawk', payout: 765, reward: 'o_contract', difficulty: 2, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 67, xp: 6 },
name: 'bravo', payout: 267, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 135, xp: 0 },
name: 'tango', payout: 1446, reward: 'honeypot', difficulty: 7, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 48, xp: 483 },
name: 'half a beer', payout: 677, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 58, xp: 75 },
name: 'hell raiser', payout: 135, reward: 'firewall', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 124, xp: 66 },
name: 'salamander', payout: 135, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 110, xp: 970 },
name: 'chico', payout: 750, reward: 'firewall', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 105, xp: 516 },
name: 'anvil', payout: 1526, reward: 'none', difficulty: 11, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 109, xp: 484 },
name: 'jam out clam out', payout: 271, reward: 'firewall', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 116, xp: 396 },
name: 'wtf', payout: 1884, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 179, xp: 114 },
name: 'hellraiser', payout: 289, reward: 'none', difficulty: 1, description: 'Aid LEO search for subject.', time_to_complete: 96, xp: 63 },
name: 'quarantine', payout: 1073, reward: 'firewall', difficulty: 7, description: 'Aid LEO search for subject.', time_to_complete: 74, xp: 133 },
name: 'turkey', payout: 1636, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 161, xp: 93 },
name: 'turkey', payout: 466, reward: 'firewall', difficulty: 12, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 73, xp: 780 },
name: 'black eye', payout: 860, reward: 'none', difficulty: 10, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 178, xp: 680 },
name: 'recovery', payout: 1246, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 124, xp: 295 },
name: 'alpha', payout: 191, reward: 'firewall', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 103, xp: 90 },
name: 'tango', payout: 1626, reward: 'none', difficulty: 12, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 169, xp: 1116 },
name: 'firesail', payout: 1249, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 145, xp: 180 },
name: 'breach', payout: 1881, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 89, xp: 568 },
name: 'wtf', payout: 76, reward: 'none', difficulty: 7, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 42, xp: 385 },
name: 'hackathon', payout: 1380, reward: 'none', difficulty: 5, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 114, xp: 110 },
name: 'wtf', payout: 575, reward: 'firewall', difficulty: 3, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 168, xp: 24 },
name: 'black eye', payout: 1550, reward: 'firewall', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 105, xp: 12 },
name: 'taco', payout: 1690, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 119, xp: 110 },
name: 'goat cheese', payout: 194, reward: 'none', difficulty: 12, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 70, xp: 324 },
name: 'salamander', payout: 1153, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 66, xp: 324 },
name: 'typhoon', payout: 1412, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 85, xp: 12 },
name: 'hackathon', payout: 1837, reward: 'none', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 166, xp: 252 },
name: 'thunder****', payout: 1958, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 82, xp: 120 },
name: 'top gun', payout: 119, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 112, xp: 200 },
name: 'hardball', payout: 493, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 179, xp: 150 },
name: 'hellraiser', payout: 1625, reward: 'o_contract', difficulty: 5, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 44, xp: 480 },
name: 'richard', payout: 563, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 126, xp: 600 },
name: 'second coming', payout: 332, reward: 'honeypot', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 160, xp: 675 },
name: 'chico', payout: 181, reward: 'firewall', difficulty: 3, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 103, xp: 213 },
name: 'shutdown', payout: 361, reward: 'honeypot', difficulty: 9, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 138, xp: 639 },
name: 'half a beer', payout: 878, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 65, xp: 156 },
name: 'false idol', payout: 1095, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 87, xp: 176 },
name: 'black hawk', payout: 378, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 122, xp: 40 },
name: 'purple donkey', payout: 1115, reward: 'firewall', difficulty: 3, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 51, xp: 270 },
name: 'snake eater', payout: 1695, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 139, xp: 220 },
name: 'thunder****', payout: 474, reward: 'none', difficulty: 3, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 31, xp: 192 },
name: 'applesauce', payout: 254, reward: 'honeypot', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 51, xp: 308 },
name: 'gibbon', payout: 1463, reward: 'firewall', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 78, xp: 444 },
name: 'richard', payout: 924, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 61, xp: 136 },
name: 'juicy', payout: 1860, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 69, xp: 561 },
name: 'applesauce', payout: 1431, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 155, xp: 62 },
name: 'top gun', payout: 735, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 81, xp: 765 },
name: 'wtf', payout: 1665, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 63, xp: 72 },
name: 'recovery', payout: 974, reward: 'none', difficulty: 2, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 63, xp: 60 },
name: 'little boy', payout: 469, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 72, xp: 142 },
name: 'snake eater', payout: 1301, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 98, xp: 365 },
name: 'baboon', payout: 1526, reward: 'o_contract', difficulty: 10, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 94, xp: 740 },
name: 'moose', payout: 1244, reward: 'zero_day', difficulty: 9, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 47, xp: 315 },
name: 'smokescreen', payout: 544, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 171, xp: 5 },
name: 'thunder****', payout: 1552, reward: 'zero_day', difficulty: 3, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 138, xp: 210 },
name: 'brown nose', payout: 798, reward: 'o_contract', difficulty: 5, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 109, xp: 210 },
name: 'gale', payout: 557, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 123, xp: 116 },
name: 'blowback', payout: 1807, reward: 'none', difficulty: 5, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 83, xp: 55 },
name: 'vigo', payout: 1730, reward: 'firewall', difficulty: 5, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 56, xp: 210 },
name: 'bannana? bannanna?', payout: 715, reward: 'firewall', difficulty: 5, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 72, xp: 50 },
name: 'thunder****', payout: 1297, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 148, xp: 396 },
name: 'moose', payout: 89, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 81, xp: 40 },
name: 'moose', payout: 799, reward: 'honeypot', difficulty: 11, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 81, xp: 814 },
name: 'juicy', payout: 1582, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 146, xp: 270 },
name: 'jaba', payout: 978, reward: 'none', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 128, xp: 170 },
name: 'muffintop', payout: 261, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 92, xp: 240 },
name: 'breach', payout: 1486, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 125, xp: 217 },
name: 'hurricane', payout: 791, reward: 'zero_day', difficulty: 10, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 133, xp: 660 },
name: 'hackathon', payout: 599, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 99, xp: 120 },
name: 'bern-inator', payout: 892, reward: 'honeypot', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 65, xp: 536 },
name: 'half a beer', payout: 1494, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 76, xp: 40 },
name: 'moose', payout: 1645, reward: 'o_contract', difficulty: 4, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 48, xp: 108 },
name: 'brown nose', payout: 448, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 128, xp: 979 },
name: 'turtle', payout: 513, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 35, xp: 261 },
name: 'bannana? bannanna?', payout: 629, reward: 'none', difficulty: 4, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 155, xp: 100 },
name: 'gale', payout: 1779, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 125, xp: 92 },
name: 'whateverthefuck', payout: 1692, reward: 'honeypot', difficulty: 1, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 83, xp: 98 },
name: 'hell raiser', payout: 367, reward: 'firewall', difficulty: 5, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 138, xp: 300 },
name: 'sherpa', payout: 96, reward: 'o_contract', difficulty: 11, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 155, xp: 616 },
name: 'fang', payout: 1296, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 117, xp: 201 },
name: 'f.o.b.', payout: 870, reward: 'firewall', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 156, xp: 495 },
name: 'moose', payout: 1503, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 112, xp: 328 },
name: 'jam out clam out', payout: 538, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 72, xp: 532 },
name: 'whateverthefuck', payout: 785, reward: 'firewall', difficulty: 8, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 138, xp: 216 },
name: 'little boy', payout: 213, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 175, xp: 95 },
name: 'chico', payout: 1008, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 50, xp: 150 },
name: 'blowback', payout: 271, reward: 'firewall', difficulty: 9, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 61, xp: 18 },
name: 'bern-inator', payout: 1461, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 45, xp: 900 },
name: 'victor', payout: 26, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 180, xp: 360 },
name: 'gale', payout: 210, reward: 'none', difficulty: 8, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 98, xp: 560 },
name: 'typhoon', payout: 1605, reward: 'none', difficulty: 7, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 119, xp: 329 },
name: 'black eye', payout: 1715, reward: 'o_contract', difficulty: 12, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 97, xp: 624 },
name: 'hurricane', payout: 1027, reward: 'o_contract', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 129, xp: 1008 },
name: 'chico', payout: 595, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 50, xp: 117 },
name: 'alpha', payout: 429, reward: 'zero_day', difficulty: 4, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 109, xp: 48 },
name: 'hardball', payout: 229, reward: 'none', difficulty: 5, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 48, xp: 50 },
name: 'f.o.b.', payout: 797, reward: 'none', difficulty: 2, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 56, xp: 138 },
name: 'consumnes', payout: 1359, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 152, xp: 612 },
name: 'firesail', payout: 1213, reward: 'none', difficulty: 4, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 151, xp: 196 },
name: 'papa', payout: 2, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 33, xp: 25 },
name: 'consumnes', payout: 769, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 72, xp: 36 },
name: 'fang', payout: 483, reward: 'firewall', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 39, xp: 50 },
name: 'turtle', payout: 560, reward: 'none', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 62, xp: 264 },
name: 'black hawk', payout: 852, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 38, xp: 288 },
name: 'firesail', payout: 1818, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 142, xp: 420 },
name: 'second coming', payout: 26, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 39, xp: 462 },
name: 'moose', payout: 1004, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 52, xp: 40 },
name: 'sherpa', payout: 1458, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 147, xp: 413 },
name: 'cheney', payout: 791, reward: 'zero_day', difficulty: 12, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 122, xp: 1044 },
name: 'coldcuts', payout: 856, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 152, xp: 98 },
name: 'half a beer', payout: 778, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 128, xp: 576 },
name: 'recovery', payout: 1108, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 52, xp: 45 },
name: 'turtle', payout: 14, reward: 'o_contract', difficulty: 11, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 54, xp: 913 },
name: 'quarantine', payout: 38, reward: 'o_contract', difficulty: 3, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 67, xp: 111 },
name: 'alpha', payout: 350, reward: 'zero_day', difficulty: 2, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 175, xp: 34 },
name: 'salamander', payout: 221, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 156, xp: 48 },
name: 'baboon', payout: 857, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 65, xp: 110 },
name: 'hardball', payout: 650, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 154, xp: 161 },
name: 'purple donkey', payout: 6, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 70, xp: 385 },
name: 'turtle', payout: 575, reward: 'none', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 151, xp: 585 },
name: 'hell raiser', payout: 259, reward: 'none', difficulty: 5, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 128, xp: 150 },
name: 'quarantine', payout: 173, reward: 'zero_day', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 166, xp: 108 },
name: 'gibbon', payout: 979, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 38, xp: 336 },
name: 'salamander', payout: 342, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 139, xp: 155 },
name: 'false idol', payout: 1674, reward: 'honeypot', difficulty: 8, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 102, xp: 528 },
name: 'cheney', payout: 1490, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 165, xp: 948 },
name: 'thunder****', payout: 662, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 175, xp: 644 },
name: 'blowback', payout: 1749, reward: 'none', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 147, xp: 20 },
name: 'goat cheese', payout: 1819, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 79, xp: 852 },
name: 'alpha', payout: 1824, reward: 'none', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 93, xp: 150 },
name: 'moose', payout: 1370, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 46, xp: 0 },
name: 'half a beer', payout: 815, reward: 'zero_day', difficulty: 2, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 68, xp: 48 },
name: 'victor', payout: 867, reward: 'none', difficulty: 11, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 49, xp: 506 },
name: 'false idol', payout: 1104, reward: 'zero_day', difficulty: 2, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 81, xp: 100 },
name: 'anvil', payout: 528, reward: 'firewall', difficulty: 6, description: 'Aid LEO search for subject.', time_to_complete: 42, xp: 546 },
name: 'purple donkey', payout: 286, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 168, xp: 252 },
name: 'second coming', payout: 786, reward: 'none', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 165, xp: 546 },
name: 'little boy', payout: 316, reward: 'none', difficulty: 6, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 150, xp: 570 },
name: 'f.o.b.', payout: 23, reward: 'firewall', difficulty: 9, description: 'Aid LEO search for subject.', time_to_complete: 169, xp: 270 },
name: 'coldcuts', payout: 1533, reward: 'none', difficulty: 9, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 53, xp: 135 },
name: 'bravo', payout: 478, reward: 'o_contract', difficulty: 4, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 148, xp: 112 },
name: 'jaba', payout: 934, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 119, xp: 460 },
name: 'sherpa', payout: 130, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 65, xp: 637 },
name: 'hardball', payout: 18, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 144, xp: 132 },
name: 'gibbon', payout: 1172, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 79, xp: 304 },
name: 'juicy', payout: 170, reward: 'honeypot', difficulty: 7, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 120, xp: 308 },
name: 'applesauce', payout: 1299, reward: 'firewall', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 160, xp: 880 },
name: 'f.o.b.', payout: 1872, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 75, xp: 490 },
name: 'baboon', payout: 1695, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 165, xp: 49 },
name: 'hell raiser', payout: 953, reward: 'zero_day', difficulty: 1, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 148, xp: 59 },
name: 'moose', payout: 1105, reward: 'firewall', difficulty: 10, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 162, xp: 670 },
name: 'bluejay', payout: 621, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 48, xp: 738 },
name: 'f.o.b.', payout: 158, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 155, xp: 290 },
name: 'recovery', payout: 556, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 86, xp: 21 },
name: 'turtle', payout: 748, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 33, xp: 880 },
name: 'cheney', payout: 1293, reward: 'zero_day', difficulty: 6, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 54, xp: 294 },
name: 'little boy', payout: 578, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 152, xp: 80 },
name: 'second coming', payout: 154, reward: 'o_contract', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 147, xp: 480 },
name: 'fang', payout: 1522, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 76, xp: 112 },
name: 'hell raiser', payout: 1039, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 88, xp: 441 },
name: 'applesauce', payout: 1497, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 167, xp: 460 },
name: 'baboon', payout: 756, reward: 'honeypot', difficulty: 1, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 153, xp: 13 },
name: 'half a beer', payout: 635, reward: 'none', difficulty: 9, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 99, xp: 684 },
name: 'papa', payout: 1590, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 164, xp: 704 },
name: 'trump-inator', payout: 787, reward: 'none', difficulty: 5, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 116, xp: 60 },
name: 'trump-inator', payout: 922, reward: 'none', difficulty: 6, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 83, xp: 210 },
name: 'hardball', payout: 691, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 96, xp: 64 },
name: 'fang', payout: 1858, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 179, xp: 420 },
name: 'trump-inator', payout: 722, reward: 'firewall', difficulty: 2, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 68, xp: 74 },
name: 'chico', payout: 1449, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 176, xp: 80 },
name: 'embedded', payout: 1702, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 129, xp: 440 },
name: 'richard', payout: 281, reward: 'firewall', difficulty: 7, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 51, xp: 462 },
name: 'thunder****', payout: 1420, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 79, xp: 216 },
name: 'dustoff', payout: 337, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 37, xp: 20 },
name: 'whateverthefuck', payout: 530, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 42, xp: 270 },
name: 'coldcuts', payout: 1338, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 57, xp: 510 },
name: 'bern-inator', payout: 1189, reward: 'none', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 142, xp: 828 },
name: 'smokescreen', payout: 1720, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 173, xp: 588 },
name: 'taco', payout: 1661, reward: 'none', difficulty: 6, description: 'Aid LEO search for subject.', time_to_complete: 137, xp: 162 },
name: 'vigo', payout: 1471, reward: 'firewall', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 176, xp: 165 },
name: 'snake eater', payout: 552, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 115, xp: 56 },
name: 'snake eater', payout: 1732, reward: 'none', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 127, xp: 165 },
name: 'gale', payout: 1635, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 145, xp: 68 },
name: 'tango', payout: 1662, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 156, xp: 160 },
name: 'fat man', payout: 1978, reward: 'o_contract', difficulty: 4, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 49, xp: 268 },
name: 'caboose', payout: 685, reward: 'firewall', difficulty: 9, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 109, xp: 405 },
name: 'wtf', payout: 1099, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 30, xp: 484 },
name: 'blacksmith', payout: 750, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 127, xp: 55 },
name: 'purple donkey', payout: 1800, reward: 'o_contract', difficulty: 7, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 37, xp: 455 },
name: 'sherpa', payout: 1366, reward: 'firewall', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 124, xp: 600 },
name: 'alpha', payout: 196, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 31, xp: 246 },
name: 'firesail', payout: 141, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 85, xp: 116 },
name: 'vigo', payout: 1964, reward: 'none', difficulty: 12, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 122, xp: 1200 },
name: 'half a beer', payout: 689, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 77, xp: 129 },
name: 'blowback', payout: 171, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 99, xp: 287 },
name: 'little boy', payout: 1152, reward: 'none', difficulty: 1, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 163, xp: 93 },
name: 'fang', payout: 1110, reward: 'o_contract', difficulty: 12, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 159, xp: 1008 },
name: 'taco', payout: 406, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 153, xp: 10 },
name: 'richard', payout: 1303, reward: 'none', difficulty: 2, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 116, xp: 38 },
name: 'iron eagle', payout: 4, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 156, xp: 570 },
name: 'embedded', payout: 1966, reward: 'firewall', difficulty: 4, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 87, xp: 68 },
name: 'dustoff', payout: 1855, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 109, xp: 320 },
name: 'chico', payout: 1854, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 82, xp: 380 },
name: 'breach', payout: 1077, reward: 'zero_day', difficulty: 8, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 130, xp: 680 },
name: 'wtf', payout: 547, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 169, xp: 36 },
name: 'bravo', payout: 1627, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 34, xp: 880 },
name: 'shutdown', payout: 120, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 52, xp: 350 },
name: 'trump-inator', payout: 1892, reward: 'none', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 92, xp: 104 },
name: 'black hawk', payout: 417, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 147, xp: 560 },
name: 'consumnes', payout: 1957, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 47, xp: 1032 },
name: 'hardball', payout: 1219, reward: 'none', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 35, xp: 913 },
name: 'baboon', payout: 402, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 49, xp: 567 },
name: 'salamander', payout: 1047, reward: 'firewall', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 177, xp: 480 },
name: 'bravo', payout: 723, reward: 'none', difficulty: 2, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 90, xp: 74 },
name: 'top gun', payout: 1194, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 126, xp: 111 },
name: 'bluejay', payout: 787, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 31, xp: 112 },
name: 'purple donkey', payout: 1460, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 97, xp: 75 },
name: 'bluejay', payout: 1682, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 108, xp: 54 },
name: 'juicy', payout: 524, reward: 'zero_day', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 139, xp: 420 },
name: 'wtf', payout: 500, reward: 'firewall', difficulty: 11, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 60, xp: 902 },
name: 'black eye', payout: 494, reward: 'firewall', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 107, xp: 34 },
name: 'bern-inator', payout: 109, reward: 'none', difficulty: 5, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 41, xp: 95 },
name: 'thunder****', payout: 1409, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 57, xp: 264 },
name: 'baboon', payout: 356, reward: 'firewall', difficulty: 10, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 110, xp: 960 },
name: 'hurricane', payout: 402, reward: 'o_contract', difficulty: 3, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 47, xp: 174 },
name: 'victor', payout: 1978, reward: 'none', difficulty: 7, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 73, xp: 665 },
name: 'trump-inator', payout: 720, reward: 'none', difficulty: 5, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 78, xp: 275 },
name: 'chico', payout: 1677, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 131, xp: 176 },
name: 'fat man', payout: 1722, reward: 'none', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 158, xp: 324 },
name: 'muffintop', payout: 1014, reward: 'firewall', difficulty: 4, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 50, xp: 300 },
name: 'alpha', payout: 1788, reward: 'firewall', difficulty: 3, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 58, xp: 207 },
name: 'hardball', payout: 1472, reward: 'honeypot', difficulty: 2, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 91, xp: 62 },
name: 'blacksmith', payout: 1620, reward: 'none', difficulty: 6, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 140, xp: 540 },
name: 'victor', payout: 247, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 78, xp: 363 },
name: 'brown nose', payout: 1638, reward: 'none', difficulty: 5, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 89, xp: 375 },
name: 'wtf', payout: 89, reward: 'zero_day', difficulty: 3, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 136, xp: 51 },
name: 'little boy', payout: 215, reward: 'firewall', difficulty: 12, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 111, xp: 552 },
name: 'chico', payout: 1445, reward: 'firewall', difficulty: 8, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 34, xp: 144 },
name: 'dustoff', payout: 1344, reward: 'firewall', difficulty: 12, description: 'Aid LEO search for subject.', time_to_complete: 177, xp: 996 },
name: 'smokescreen', payout: 110, reward: 'zero_day', difficulty: 11, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 45, xp: 77 },
name: 'blowback', payout: 1953, reward: 'none', difficulty: 8, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 151, xp: 192 },
name: 'trump-inator', payout: 711, reward: 'none', difficulty: 1, description: 'Aid LEO search for subject.', time_to_complete: 130, xp: 41 },
name: 'cheney', payout: 1156, reward: 'none', difficulty: 7, description: 'Aid LEO search for subject.', time_to_complete: 149, xp: 385 },
name: 'trump-inator', payout: 140, reward: 'o_contract', difficulty: 10, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 88, xp: 810 },
name: 'dustoff', payout: 134, reward: 'honeypot', difficulty: 3, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 102, xp: 135 },
name: 'little boy', payout: 1431, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 160, xp: 110 },
name: 'recovery', payout: 503, reward: 'firewall', difficulty: 3, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 120, xp: 291 },
name: 'backdraft', payout: 846, reward: 'none', difficulty: 11, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 78, xp: 1089 },
name: 'taco', payout: 987, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 117, xp: 100 },
name: 'goat cheese', payout: 727, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 35, xp: 114 },
name: 'fat man', payout: 1122, reward: 'firewall', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 34, xp: 270 },
name: 'jaba', payout: 275, reward: 'none', difficulty: 9, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 98, xp: 558 },
name: 'bravo', payout: 1753, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 33, xp: 352 },
name: 'tango', payout: 894, reward: 'none', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 180, xp: 90 },
name: 'taco', payout: 692, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 96, xp: 16 },
name: 'blowback', payout: 1586, reward: 'o_contract', difficulty: 2, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 66, xp: 160 },
name: 'richard', payout: 29, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 34, xp: 24 },
name: 'hackathon', payout: 665, reward: 'firewall', difficulty: 8, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 42, xp: 328 },
name: 'alpha', payout: 1650, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 100, xp: 616 },
name: 'second coming', payout: 84, reward: 'o_contract', difficulty: 9, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 98, xp: 549 },
name: 'little boy', payout: 1588, reward: 'honeypot', difficulty: 10, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 149, xp: 160 },
name: 'chico', payout: 1299, reward: 'o_contract', difficulty: 7, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 59, xp: 119 },
name: 'bannana? bannanna?', payout: 728, reward: 'none', difficulty: 12, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 180, xp: 252 },
name: 'alpha', payout: 1838, reward: 'o_contract', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 68, xp: 464 },
name: 'coldcuts', payout: 487, reward: 'firewall', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 99, xp: 100 },
name: 'jaba', payout: 728, reward: 'none', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 135, xp: 75 },
name: 'consumnes', payout: 1109, reward: 'firewall', difficulty: 12, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 163, xp: 144 },
name: 'bluejay', payout: 1673, reward: 'honeypot', difficulty: 1, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 30, xp: 82 },
name: 'gale', payout: 640, reward: 'o_contract', difficulty: 9, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 178, xp: 117 },
name: 'black hawk', payout: 226, reward: 'firewall', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 96, xp: 16 },
name: 'smokescreen', payout: 1299, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 49, xp: 77 },
name: 'applesauce', payout: 228, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 34, xp: 126 },
name: 'hackathon', payout: 1387, reward: 'none', difficulty: 7, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 149, xp: 63 },
name: 'firesail', payout: 1883, reward: 'firewall', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 63, xp: 36 },
name: 'bannana? bannanna?', payout: 1368, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 69, xp: 528 },
name: 'hellraiser', payout: 151, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 85, xp: 348 },
name: 'caboose', payout: 1397, reward: 'firewall', difficulty: 9, description: 'Aid LEO search for subject.', time_to_complete: 95, xp: 243 },
name: 'quarantine', payout: 1072, reward: 'zero_day', difficulty: 8, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 100, xp: 592 },
name: 'iron eagle', payout: 1398, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 116, xp: 86 },
name: 'fat man', payout: 1902, reward: 'o_contract', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 46, xp: 528 },
name: 'gibbon', payout: 831, reward: 'firewall', difficulty: 4, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 156, xp: 116 },
name: 'cheney', payout: 56, reward: 'firewall', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 114, xp: 504 },
name: 'hellraiser', payout: 537, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 169, xp: 66 },
name: 'muffintop', payout: 413, reward: 'firewall', difficulty: 8, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 56, xp: 640 },
name: 'hellraiser', payout: 1159, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 65, xp: 32 },
name: 'false idol', payout: 663, reward: 'firewall', difficulty: 12, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 123, xp: 696 },
name: 'trump-inator', payout: 1727, reward: 'none', difficulty: 3, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 125, xp: 222 }
]
    )
