# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

t = Time.now + 3

users = User.create(
  [
    { name: 'alice', password: 'a', firewall: 5, honeypot: 2, zeroday: 2 },    
    { name: 'bob', password: 'b', firewall: 2, honeypot: 2, active_firewall: 5, active_honeypot: 3 },    
    { name: 'charlie', password: 'c' },    
    { name: 'david', password: 'd' }    
  ]
)

breaches = Breach.create(
  [
    #alice is targeting bob OR bob is targeted by alice
    {user_id: 1, target_id: 2, breached: false},
    {user_id: 1, target_id: 3, breached: true, cash_stolen: 1000},
    {user_id: 1, target_id: 2, breached: false},

    {user_id: 2, target_id: 1, breached: false},
    {user_id: 2, target_id: 4, breached: false},

    {user_id: 3, target_id: 1, breached: false},

    {user_id: 4, target_id: 1, breached: false},
    {user_id: 4, target_id: 2, breached: false}
  ]
)

operatives = Operative.create(
  [
    { user_id: 1, name: 'Smiling Gibbon', status: 'deployed', skill: 7, job_id: 1 },
    { user_id: 1, name: 'Sitting Tofu', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Fuze', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Black Swan', status: 'mia', skill: 3, job_id: nil },

    { user_id: 2, name: 'Daft Adder', status: 'injured', skill: 6, job_id: nil },
    { user_id: 2, name: 'Stale Hammer', status: 'deployed', skill: 2, job_id: nil },
    { user_id: 2, name: 'Orange Rocket', status: 'deployed', skill: 3, job_id: nil },
    { user_id: 2, name: 'Steel Sun', status: 'deployed', skill: 4, job_id: nil },

    { user_id: 4, name: 'Yoga', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Cunning Turtle', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Gypsy', status: 'dead', skill: 4, job_id: nil },
    { user_id: 4, name: 'Alpha', status: 'mia', skill: 8, job_id: nil }

  ]
)


jobs = Job.create(
    [
{name: 'second coming', payout: 482, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 129, xp: 279 },
{name: 'moose', payout: 211, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 153, xp: 780 },
{name: 'fat man', payout: 1255, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 124, xp: 708 },
{name: 'victor', payout: 1472, reward: 'none', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 41, xp: 972 },
{name: 'little boy', payout: 839, reward: 'firewall', difficulty: 9, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 38, xp: 810 },
{name: 'false idol', payout: 1169, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 134, xp: 114 },
{name: 'little boy', payout: 1500, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 116, xp: 680 },
{name: 'breach', payout: 876, reward: 'o_contract', difficulty: 9, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 60, xp: 522 },
{name: 'bluejay', payout: 1901, reward: 'firewall', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 96, xp: 19 },
{name: 'blacksmith', payout: 1870, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 40, xp: 39 },
{name: 'hell raiser', payout: 247, reward: 'none', difficulty: 7, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 92, xp: 63 },
{name: 'blowback', payout: 693, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 56, xp: 70 },
{name: 'embedded', payout: 511, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 59, xp: 828 },
{name: 'embedded', payout: 712, reward: 'none', difficulty: 12, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 129, xp: 540 },
{name: 'cheney', payout: 383, reward: 'firewall', difficulty: 12, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 97, xp: 720 },
{name: 'tango', payout: 1383, reward: 'none', difficulty: 2, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 65, xp: 96 },
{name: 'shutdown', payout: 1225, reward: 'honeypot', difficulty: 10, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 92, xp: 180 },
{name: 'backdraft', payout: 238, reward: 'firewall', difficulty: 10, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 179, xp: 410 },
{name: 'turtle', payout: 1495, reward: 'firewall', difficulty: 9, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 153, xp: 27 },
{name: 'muffintop', payout: 1900, reward: 'firewall', difficulty: 7, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 44, xp: 511 },
{name: 'juicy', payout: 1856, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 113, xp: 528 },
{name: 'goat cheese', payout: 1913, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 110, xp: 126 },
{name: 'breach', payout: 408, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 129, xp: 300 },
{name: 'turtle', payout: 1365, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 113, xp: 98 },
{name: 'top gun', payout: 1455, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 150, xp: 220 },
{name: 'salamander', payout: 1544, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 87, xp: 52 },
{name: 'papa', payout: 93, reward: 'none', difficulty: 1, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 97, xp: 74 },
{name: 'jam out clam out', payout: 1220, reward: 'o_contract', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 158, xp: 444 },
{name: 'brown nose', payout: 761, reward: 'firewall', difficulty: 8, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 119, xp: 184 },
{name: 'fang', payout: 1196, reward: 'none', difficulty: 4, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 97, xp: 36 },
{name: 'salamander', payout: 1214, reward: 'none', difficulty: 9, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 104, xp: 837 },
{name: 'half a beer', payout: 1949, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 65, xp: 488 },
{name: 'bern-inator', payout: 1724, reward: 'none', difficulty: 7, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 97, xp: 483 },
{name: 'loose goose', payout: 677, reward: 'honeypot', difficulty: 9, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 36, xp: 621 },
{name: 'purple donkey', payout: 915, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 50, xp: 66 },
{name: 'caboose', payout: 1460, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 175, xp: 384 },
{name: 'tango', payout: 529, reward: 'firewall', difficulty: 10, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 59, xp: 830 },
{name: 'typhoon', payout: 1013, reward: 'none', difficulty: 8, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 111, xp: 224 },
{name: 'tango', payout: 135, reward: 'firewall', difficulty: 2, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 119, xp: 178 },
{name: 'fang', payout: 1140, reward: 'zero_day', difficulty: 5, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 162, xp: 410 },
{name: 'fang', payout: 1539, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 33, xp: 600 },
{name: 'purple donkey', payout: 1372, reward: 'firewall', difficulty: 2, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 178, xp: 48 },
{name: 'victor', payout: 920, reward: 'o_contract', difficulty: 9, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 157, xp: 882 },
{name: 'consumnes', payout: 152, reward: 'firewall', difficulty: 8, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 50, xp: 560 },
{name: 'caboose', payout: 229, reward: 'firewall', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 171, xp: 460 },
{name: 'sherpa', payout: 991, reward: 'firewall', difficulty: 4, description: 'Aid LEO search for subject.', time_to_complete: 49, xp: 400 },
{name: 'papa', payout: 736, reward: 'firewall', difficulty: 3, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 108, xp: 192 },
{name: 'loose goose', payout: 348, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 74, xp: 42 },
{name: 'cheney', payout: 1665, reward: 'o_contract', difficulty: 5, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 72, xp: 490 },
{name: 'loose goose', payout: 1779, reward: 'firewall', difficulty: 3, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 134, xp: 27 },
{name: 'vigo', payout: 1202, reward: 'firewall', difficulty: 11, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 79, xp: 704 },
{name: 'brown nose', payout: 1057, reward: 'none', difficulty: 8, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 94, xp: 384 },
{name: 'salamander', payout: 1336, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 123, xp: 324 },
{name: 'consumnes', payout: 440, reward: 'firewall', difficulty: 10, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 157, xp: 160 },
{name: 'chico', payout: 1535, reward: 'none', difficulty: 12, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 146, xp: 204 },
{name: 'iron eagle', payout: 1241, reward: 'none', difficulty: 3, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 167, xp: 45 },
{name: 'brown nose', payout: 930, reward: 'firewall', difficulty: 7, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 160, xp: 637 },
{name: 'bern-inator', payout: 1827, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 139, xp: 686 },
{name: 'f.o.b.', payout: 1954, reward: 'o_contract', difficulty: 2, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 145, xp: 28 },
{name: 'fat man', payout: 1729, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 80, xp: 310 },
{name: 'whateverthefuck', payout: 952, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 147, xp: 159 },
{name: 'firesail', payout: 634, reward: 'firewall', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 139, xp: 75 },
{name: 'loose goose', payout: 850, reward: 'none', difficulty: 2, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 78, xp: 146 },
{name: 'typhoon', payout: 111, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 39, xp: 106 },
{name: 'turkey', payout: 1146, reward: 'none', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 41, xp: 380 },
{name: 'f.o.b.', payout: 392, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 62, xp: 8 },
{name: 'richard', payout: 1266, reward: 'none', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 137, xp: 128 },
{name: 'top gun', payout: 951, reward: 'none', difficulty: 8, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 108, xp: 520 },
{name: 'cheney', payout: 25, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 133, xp: 148 },
{name: 'anvil', payout: 1215, reward: 'none', difficulty: 1, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 121, xp: 95 },
{name: 'loose goose', payout: 1236, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 134, xp: 282 },
{name: 'trump-inator', payout: 1467, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 88, xp: 295 },
{name: 'baboon', payout: 1807, reward: 'o_contract', difficulty: 11, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 122, xp: 0 },
{name: 'turtle', payout: 535, reward: 'firewall', difficulty: 7, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 179, xp: 553 },
{name: 'recovery', payout: 1789, reward: 'none', difficulty: 7, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 73, xp: 112 },
{name: 'second coming', payout: 710, reward: 'none', difficulty: 9, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 118, xp: 720 },
{name: 'richard', payout: 1178, reward: 'none', difficulty: 9, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 70, xp: 846 },
{name: 'purple donkey', payout: 1291, reward: 'none', difficulty: 4, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 99, xp: 200 },
{name: 'jaba', payout: 93, reward: 'honeypot', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 137, xp: 852 },
{name: 'embedded', payout: 1448, reward: 'none', difficulty: 1, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 89, xp: 94 },
{name: 'jaba', payout: 158, reward: 'none', difficulty: 4, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 61, xp: 228 },
{name: 'embedded', payout: 1728, reward: 'firewall', difficulty: 6, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 180, xp: 438 },
{name: 'snake eater', payout: 207, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 44, xp: 336 },
{name: 'half a beer', payout: 1982, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 53, xp: 504 },
{name: 'smokescreen', payout: 505, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 122, xp: 174 },
{name: 'vigo', payout: 886, reward: 'o_contract', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 67, xp: 160 },
{name: 'applesauce', payout: 1141, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 75, xp: 776 },
{name: 'smokescreen', payout: 170, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 152, xp: 516 },
{name: 'recovery', payout: 1915, reward: 'none', difficulty: 6, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 90, xp: 240 },
{name: 'hell raiser', payout: 606, reward: 'none', difficulty: 11, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 148, xp: 858 },
{name: 'muffintop', payout: 846, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 141, xp: 189 },
{name: 'breach', payout: 1807, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 54, xp: 684 },
{name: 'baboon', payout: 358, reward: 'none', difficulty: 9, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 150, xp: 567 },
{name: 'juicy', payout: 776, reward: 'none', difficulty: 6, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 146, xp: 540 },
{name: 'papa', payout: 421, reward: 'none', difficulty: 6, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 49, xp: 348 },
{name: 'bravo', payout: 1653, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 109, xp: 636 },
{name: 'caboose', payout: 596, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 113, xp: 702 },
{name: 'smokescreen', payout: 124, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 59, xp: 133 },
{name: 'applesauce', payout: 528, reward: 'firewall', difficulty: 2, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 127, xp: 10 },
{name: 'false idol', payout: 1746, reward: 'firewall', difficulty: 4, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 160, xp: 36 },
{name: 'bluejay', payout: 1996, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 166, xp: 60 },
{name: 'consumnes', payout: 1886, reward: 'o_contract', difficulty: 3, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 93, xp: 3 },
{name: 'blacksmith', payout: 349, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 55, xp: 220 },
{name: 'baboon', payout: 1496, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 77, xp: 441 },
{name: 'fat man', payout: 1915, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 81, xp: 235 },
{name: 'embedded', payout: 731, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 113, xp: 209 },
{name: 'hurricane', payout: 1202, reward: 'none', difficulty: 12, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 133, xp: 1020 },
{name: 'false idol', payout: 441, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 154, xp: 276 },
{name: 'jaba', payout: 271, reward: 'firewall', difficulty: 4, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 120, xp: 364 },
{name: 'black eye', payout: 268, reward: 'none', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 139, xp: 0 },
{name: 'caboose', payout: 851, reward: 'zero_day', difficulty: 6, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 41, xp: 228 },
{name: 'thunder****', payout: 821, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 163, xp: 385 },
{name: 'quarantine', payout: 1077, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 171, xp: 126 },
{name: 'anvil', payout: 1603, reward: 'none', difficulty: 8, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 126, xp: 192 },
{name: 'salamander', payout: 1146, reward: 'firewall', difficulty: 1, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 133, xp: 54 },
{name: 'thunder****', payout: 647, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 46, xp: 8 },
{name: 'dustoff', payout: 1569, reward: 'firewall', difficulty: 8, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 94, xp: 200 },
{name: 'turtle', payout: 379, reward: 'none', difficulty: 12, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 145, xp: 984 },
{name: 'muffintop', payout: 1142, reward: 'none', difficulty: 8, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 91, xp: 504 },
{name: 'turkey', payout: 1185, reward: 'none', difficulty: 12, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 93, xp: 288 },
{name: 'black eye', payout: 350, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 168, xp: 882 },
{name: 'hackathon', payout: 1451, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 105, xp: 756 },
{name: 'baboon', payout: 1897, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 86, xp: 120 },
{name: 'breach', payout: 970, reward: 'firewall', difficulty: 8, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 141, xp: 192 },
{name: 'breach', payout: 772, reward: 'honeypot', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 64, xp: 744 },
{name: 'trump-inator', payout: 1520, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 77, xp: 468 },
{name: 'smokescreen', payout: 302, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 99, xp: 35 },
{name: 'black hawk', payout: 1454, reward: 'firewall', difficulty: 4, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 115, xp: 252 },
{name: 'embedded', payout: 1590, reward: 'none', difficulty: 6, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 131, xp: 348 },
{name: 'smokescreen', payout: 92, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 110, xp: 165 },
{name: 'bravo', payout: 719, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 110, xp: 72 },
{name: 'gale', payout: 1385, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 35, xp: 500 },
{name: 'bannana? bannanna?', payout: 1202, reward: 'none', difficulty: 11, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 148, xp: 825 },
{name: 'consumnes', payout: 322, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 87, xp: 204 },
{name: 'recovery', payout: 428, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 134, xp: 240 },
{name: 'whateverthefuck', payout: 28, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 178, xp: 399 },
{name: 'shutdown', payout: 579, reward: 'none', difficulty: 12, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 121, xp: 492 },
{name: 'fang', payout: 1524, reward: 'firewall', difficulty: 6, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 170, xp: 0 },
{name: 'fang', payout: 1913, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 157, xp: 469 },
{name: 'brown nose', payout: 389, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 43, xp: 550 },
{name: 'gibbon', payout: 142, reward: 'firewall', difficulty: 10, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 57, xp: 630 },
{name: 'victor', payout: 1422, reward: 'none', difficulty: 3, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 131, xp: 159 },
{name: 'taco', payout: 47, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 102, xp: 279 },
{name: 'bern-inator', payout: 1910, reward: 'none', difficulty: 3, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 84, xp: 156 },
{name: 'fang', payout: 344, reward: 'firewall', difficulty: 1, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 139, xp: 94 },
{name: 'papa', payout: 217, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 130, xp: 540 },
{name: 'hellraiser', payout: 1888, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 96, xp: 39 },
{name: 'caboose', payout: 933, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 164, xp: 288 },
{name: 'little boy', payout: 1145, reward: 'none', difficulty: 3, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 40, xp: 33 },
{name: 'caboose', payout: 777, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 157, xp: 600 },
{name: 'coldcuts', payout: 1867, reward: 'zero_day', difficulty: 7, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 37, xp: 322 },
{name: 'moose', payout: 973, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 64, xp: 440 },
{name: 'baboon', payout: 185, reward: 'none', difficulty: 4, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 57, xp: 296 },
{name: 'typhoon', payout: 1046, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 96, xp: 328 },
{name: 'gibbon', payout: 1796, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 82, xp: 60 },
{name: 'trump-inator', payout: 1417, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 160, xp: 213 },
{name: 'juicy', payout: 1416, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 174, xp: 42 },
{name: 'bravo', payout: 802, reward: 'honeypot', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 119, xp: 396 },
{name: 'black hawk', payout: 186, reward: 'honeypot', difficulty: 4, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 155, xp: 176 },
{name: 'little boy', payout: 448, reward: 'zero_day', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 115, xp: 122 },
{name: 'f.o.b.', payout: 1406, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 117, xp: 477 },
{name: 'jaba', payout: 823, reward: 'none', difficulty: 8, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 126, xp: 232 },
{name: 'thunder****', payout: 1814, reward: 'none', difficulty: 12, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 172, xp: 396 },
{name: 'black eye', payout: 873, reward: 'none', difficulty: 8, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 168, xp: 512 },
{name: 'little boy', payout: 1996, reward: 'honeypot', difficulty: 6, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 107, xp: 138 },
{name: 'goat cheese', payout: 457, reward: 'honeypot', difficulty: 5, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 175, xp: 0 },
{name: 'backdraft', payout: 1651, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 95, xp: 320 },
{name: 'typhoon', payout: 875, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 136, xp: 16 },
{name: 'coldcuts', payout: 1634, reward: 'none', difficulty: 3, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 167, xp: 114 },
{name: 'shutdown', payout: 211, reward: 'firewall', difficulty: 11, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 56, xp: 308 },
{name: 'smokescreen', payout: 1545, reward: 'none', difficulty: 7, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 92, xp: 91 },
{name: 'salamander', payout: 1458, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 61, xp: 376 },
{name: 'purple donkey', payout: 624, reward: 'none', difficulty: 3, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 69, xp: 240 },
{name: 'applesauce', payout: 1322, reward: 'zero_day', difficulty: 7, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 139, xp: 217 },
{name: 'top gun', payout: 1595, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 50, xp: 40 },
{name: 'snake eater', payout: 862, reward: 'honeypot', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 109, xp: 329 },
{name: 'turkey', payout: 567, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 138, xp: 224 },
{name: 'second coming', payout: 1554, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 173, xp: 388 },
{name: 'top gun', payout: 1599, reward: 'firewall', difficulty: 8, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 119, xp: 424 },
{name: 'firesail', payout: 467, reward: 'none', difficulty: 2, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 103, xp: 26 },
{name: 'hardball', payout: 1545, reward: 'firewall', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 159, xp: 48 },
{name: 'brown nose', payout: 1018, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 60, xp: 208 },
{name: 'hell raiser', payout: 1823, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 141, xp: 830 },
{name: 'typhoon', payout: 1365, reward: 'zero_day', difficulty: 4, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 130, xp: 28 },
{name: 'hell raiser', payout: 1307, reward: 'firewall', difficulty: 2, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 142, xp: 46 },
{name: 'dustoff', payout: 687, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 94, xp: 365 },
{name: 'hellraiser', payout: 741, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 106, xp: 99 },
{name: 'top gun', payout: 149, reward: 'none', difficulty: 3, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 103, xp: 90 },
{name: 'bravo', payout: 735, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 115, xp: 696 },
{name: 'jaba', payout: 567, reward: 'o_contract', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 124, xp: 290 },
{name: 'black eye', payout: 1847, reward: 'firewall', difficulty: 4, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 176, xp: 352 },
{name: 'bannana? bannanna?', payout: 1715, reward: 'zero_day', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 178, xp: 37 },
{name: 'juicy', payout: 1642, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 76, xp: 207 },
{name: 'half a beer', payout: 160, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 57, xp: 500 },
{name: 'jaba', payout: 1293, reward: 'none', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 123, xp: 504 },
{name: 'chico', payout: 1160, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 80, xp: 957 },
{name: 'cheney', payout: 650, reward: 'none', difficulty: 11, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 127, xp: 385 },
{name: 'recovery', payout: 577, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 81, xp: 48 },
{name: 'richard', payout: 93, reward: 'o_contract', difficulty: 1, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 38, xp: 90 },
{name: 'chico', payout: 1303, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 141, xp: 120 },
{name: 'whateverthefuck', payout: 1553, reward: 'honeypot', difficulty: 1, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 158, xp: 12 },
{name: 'turkey', payout: 1344, reward: 'honeypot', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 149, xp: 178 },
{name: 'embedded', payout: 941, reward: 'honeypot', difficulty: 8, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 148, xp: 296 },
{name: 'purple donkey', payout: 1269, reward: 'o_contract', difficulty: 8, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 122, xp: 8 },
{name: 'alpha', payout: 540, reward: 'zero_day', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 166, xp: 640 },
{name: 'juicy', payout: 146, reward: 'o_contract', difficulty: 2, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 103, xp: 190 },
{name: 'cheney', payout: 1260, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 84, xp: 130 },
{name: 'thunder****', payout: 21, reward: 'honeypot', difficulty: 12, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 148, xp: 828 },
{name: 'caboose', payout: 584, reward: 'none', difficulty: 5, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 94, xp: 100 },
{name: 'iron eagle', payout: 643, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 86, xp: 360 },
{name: 'shutdown', payout: 1895, reward: 'none', difficulty: 4, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 66, xp: 144 },
{name: 'hurricane', payout: 1286, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 77, xp: 192 },
{name: 'embedded', payout: 460, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 129, xp: 760 },
{name: 'f.o.b.', payout: 85, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 44, xp: 425 },
{name: 'smokescreen', payout: 1156, reward: 'firewall', difficulty: 9, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 57, xp: 162 },
{name: 'moose', payout: 97, reward: 'firewall', difficulty: 2, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 153, xp: 130 },
{name: 'fang', payout: 1126, reward: 'none', difficulty: 1, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 83, xp: 34 },
{name: 'gibbon', payout: 1152, reward: 'honeypot', difficulty: 4, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 39, xp: 400 },
{name: 'black hawk', payout: 2000, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 120, xp: 39 },
{name: 'anvil', payout: 512, reward: 'zero_day', difficulty: 12, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 35, xp: 1044 },
{name: 'salamander', payout: 1201, reward: 'none', difficulty: 6, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 149, xp: 276 },
{name: 'salamander', payout: 1976, reward: 'none', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 116, xp: 126 },
{name: 'snake eater', payout: 703, reward: 'none', difficulty: 3, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 165, xp: 6 },
{name: 'fang', payout: 45, reward: 'none', difficulty: 9, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 141, xp: 828 },
{name: 'brown nose', payout: 270, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 72, xp: 236 },
{name: 'second coming', payout: 1490, reward: 'none', difficulty: 8, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 134, xp: 448 },
{name: 'caboose', payout: 518, reward: 'none', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 85, xp: 70 },
{name: 'gibbon', payout: 1749, reward: 'firewall', difficulty: 8, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 73, xp: 96 },
{name: 'wtf', payout: 624, reward: 'honeypot', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 52, xp: 242 },
{name: 'recovery', payout: 1587, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 37, xp: 6 },
{name: 'trump-inator', payout: 40, reward: 'firewall', difficulty: 8, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 163, xp: 720 },
{name: 'goat cheese', payout: 433, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 150, xp: 275 },
{name: 'backdraft', payout: 1607, reward: 'none', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 78, xp: 134 },
{name: 'caboose', payout: 1916, reward: 'firewall', difficulty: 4, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 71, xp: 256 },
{name: 'fang', payout: 192, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 132, xp: 244 },
{name: 'gale', payout: 1735, reward: 'none', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 91, xp: 210 },
{name: 'blowback', payout: 800, reward: 'none', difficulty: 9, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 138, xp: 774 },
{name: 'jam out clam out', payout: 1738, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 105, xp: 150 },
{name: 'coldcuts', payout: 1516, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 147, xp: 284 },
{name: 'hurricane', payout: 1598, reward: 'none', difficulty: 11, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 134, xp: 770 },
{name: 'goat cheese', payout: 1445, reward: 'firewall', difficulty: 2, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 71, xp: 74 },
{name: 'salamander', payout: 402, reward: 'none', difficulty: 4, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 30, xp: 340 },
{name: 'breach', payout: 536, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 45, xp: 124 },
{name: 'jam out clam out', payout: 1914, reward: 'none', difficulty: 7, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 136, xp: 588 },
{name: 'tango', payout: 1877, reward: 'none', difficulty: 4, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 174, xp: 336 },
{name: 'loose goose', payout: 1835, reward: 'honeypot', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 129, xp: 282 },
{name: 'jaba', payout: 1271, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 86, xp: 210 },
{name: 'firesail', payout: 1468, reward: 'none', difficulty: 2, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 106, xp: 24 },
{name: 'recovery', payout: 587, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 73, xp: 858 },
{name: 'whateverthefuck', payout: 1658, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 52, xp: 825 },
{name: 'bern-inator', payout: 1237, reward: 'firewall', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 44, xp: 74 },
{name: 'vigo', payout: 190, reward: 'none', difficulty: 5, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 126, xp: 470 },
{name: 'hackathon', payout: 1684, reward: 'honeypot', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 115, xp: 4 },
{name: 'breach', payout: 1465, reward: 'firewall', difficulty: 1, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 161, xp: 1 },
{name: 'iron eagle', payout: 1926, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 153, xp: 86 },
{name: 'jam out clam out', payout: 1927, reward: 'o_contract', difficulty: 12, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 148, xp: 36 },
{name: 'firesail', payout: 955, reward: 'zero_day', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 121, xp: 20 },
{name: 'bluejay', payout: 824, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 150, xp: 315 },
{name: 'bluejay', payout: 739, reward: 'firewall', difficulty: 8, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 147, xp: 624 },
{name: 'muffintop', payout: 604, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 102, xp: 430 },
{name: 'moose', payout: 955, reward: 'honeypot', difficulty: 6, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 168, xp: 480 },
{name: 'gale', payout: 1652, reward: 'none', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 43, xp: 375 },
{name: 'backdraft', payout: 1445, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 115, xp: 225 },
{name: 'muffintop', payout: 337, reward: 'firewall', difficulty: 2, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 117, xp: 48 },
{name: 'moose', payout: 1652, reward: 'honeypot', difficulty: 1, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 44, xp: 2 },
{name: 'cheney', payout: 745, reward: 'zero_day', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 123, xp: 90 },
{name: 'brown nose', payout: 1596, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 145, xp: 140 },
{name: 'juicy', payout: 1599, reward: 'o_contract', difficulty: 8, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 111, xp: 712 },
{name: 'top gun', payout: 1598, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 147, xp: 416 },
{name: 'top gun', payout: 389, reward: 'honeypot', difficulty: 5, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 67, xp: 395 },
{name: 'bravo', payout: 1420, reward: 'firewall', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 78, xp: 94 },
{name: 'half a beer', payout: 505, reward: 'firewall', difficulty: 8, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 99, xp: 488 },
{name: 'purple donkey', payout: 1915, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 30, xp: 539 },
{name: 'typhoon', payout: 1628, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 163, xp: 350 },
{name: 'sherpa', payout: 914, reward: 'none', difficulty: 6, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 178, xp: 12 },
{name: 'second coming', payout: 792, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 81, xp: 270 },
{name: 'hellraiser', payout: 787, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 149, xp: 752 },
{name: 'second coming', payout: 1546, reward: 'firewall', difficulty: 11, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 97, xp: 517 },
{name: 'baboon', payout: 89, reward: 'o_contract', difficulty: 2, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 43, xp: 120 },
{name: 'shutdown', payout: 693, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 137, xp: 200 },
{name: 'breach', payout: 1887, reward: 'firewall', difficulty: 4, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 57, xp: 240 },
{name: 'hurricane', payout: 1749, reward: 'none', difficulty: 12, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 112, xp: 852 },
{name: 'shutdown', payout: 1666, reward: 'firewall', difficulty: 9, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 98, xp: 774 },
{name: 'breach', payout: 777, reward: 'o_contract', difficulty: 5, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 136, xp: 45 },
{name: 'applesauce', payout: 110, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 72, xp: 460 },
{name: 'hackathon', payout: 634, reward: 'zero_day', difficulty: 6, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 126, xp: 282 },
{name: 'f.o.b.', payout: 1702, reward: 'none', difficulty: 6, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 117, xp: 534 },
{name: 'hardball', payout: 1949, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 169, xp: 168 },
{name: 'jam out clam out', payout: 832, reward: 'none', difficulty: 6, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 128, xp: 138 },
{name: 'blowback', payout: 1036, reward: 'none', difficulty: 7, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 75, xp: 406 },
{name: 'bern-inator', payout: 769, reward: 'firewall', difficulty: 1, description: 'Aid LEO search for subject.', time_to_complete: 40, xp: 36 },
{name: 'taco', payout: 662, reward: 'none', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 63, xp: 74 },
{name: 'little boy', payout: 479, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 100, xp: 188 },
{name: 'firesail', payout: 1965, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 72, xp: 28 },
{name: 'purple donkey', payout: 313, reward: 'firewall', difficulty: 12, description: 'Aid LEO search for subject.', time_to_complete: 59, xp: 624 },
{name: 'false idol', payout: 1904, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 85, xp: 256 },
{name: 'applesauce', payout: 856, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 45, xp: 4 },
{name: 'little boy', payout: 1036, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 128, xp: 770 },
{name: 'cheney', payout: 1591, reward: 'zero_day', difficulty: 8, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 32, xp: 544 },
{name: 'dustoff', payout: 624, reward: 'none', difficulty: 11, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 98, xp: 33 },
{name: 'thunder****', payout: 788, reward: 'firewall', difficulty: 1, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 167, xp: 94 },
{name: 'backdraft', payout: 86, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 167, xp: 760 },
{name: 'turkey', payout: 462, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 164, xp: 264 },
{name: 'snake eater', payout: 1805, reward: 'firewall', difficulty: 11, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 160, xp: 957 },
{name: 'anvil', payout: 68, reward: 'firewall', difficulty: 3, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 111, xp: 207 },
{name: 'sherpa', payout: 1467, reward: 'firewall', difficulty: 3, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 64, xp: 264 },
{name: 'little boy', payout: 289, reward: 'zero_day', difficulty: 12, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 39, xp: 708 },
{name: 'black hawk', payout: 1906, reward: 'none', difficulty: 3, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 163, xp: 192 },
{name: 'dustoff', payout: 642, reward: 'none', difficulty: 3, description: 'VIP blackmail suspects located.  Seek/destroy approved.  No disintegrations.', time_to_complete: 130, xp: 213 },
{name: 'backdraft', payout: 1790, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 123, xp: 245 },
{name: 'muffintop', payout: 972, reward: 'firewall', difficulty: 7, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 52, xp: 602 },
{name: 'purple donkey', payout: 533, reward: 'none', difficulty: 6, description: 'Aid LEO search for subject.', time_to_complete: 86, xp: 54 },
{name: 'hellraiser', payout: 1145, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 110, xp: 464 },
{name: 'second coming', payout: 1018, reward: 'firewall', difficulty: 3, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 108, xp: 213 },
{name: 'black eye', payout: 1628, reward: 'none', difficulty: 6, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 63, xp: 288 },
{name: 'sherpa', payout: 374, reward: 'none', difficulty: 6, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 115, xp: 18 },
{name: 'black eye', payout: 624, reward: 'firewall', difficulty: 2, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 99, xp: 104 },
{name: 'purple donkey', payout: 1286, reward: 'zero_day', difficulty: 7, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 88, xp: 693 },
{name: 'consumnes', payout: 157, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 137, xp: 80 },
{name: 'baboon', payout: 1866, reward: 'firewall', difficulty: 12, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 162, xp: 312 },
{name: 'caboose', payout: 1853, reward: 'none', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 48, xp: 595 },
{name: 'hardball', payout: 1845, reward: 'firewall', difficulty: 10, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 161, xp: 920 },
{name: 'tango', payout: 1687, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 41, xp: 638 },
{name: 'little boy', payout: 393, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 118, xp: 190 },
{name: 'applesauce', payout: 1716, reward: 'firewall', difficulty: 1, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 105, xp: 29 },
{name: 'cheney', payout: 1507, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 37, xp: 356 },
{name: 'jaba', payout: 1258, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 173, xp: 264 },
{name: 'turkey', payout: 824, reward: 'honeypot', difficulty: 10, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 140, xp: 840 },
{name: 'chico', payout: 1835, reward: 'firewall', difficulty: 10, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 72, xp: 980 },
{name: 'baboon', payout: 618, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 145, xp: 304 },
{name: 'hurricane', payout: 493, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 86, xp: 418 },
{name: 'juicy', payout: 1978, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 62, xp: 75 },
{name: 'moose', payout: 739, reward: 'o_contract', difficulty: 12, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 114, xp: 600 },
{name: 'bluejay', payout: 32, reward: 'o_contract', difficulty: 12, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 148, xp: 372 },
{name: 'firesail', payout: 647, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 35, xp: 950 },
{name: 'top gun', payout: 1981, reward: 'zero_day', difficulty: 4, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 69, xp: 216 },
{name: 'loose goose', payout: 1077, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 162, xp: 132 },
{name: 'consumnes', payout: 1417, reward: 'none', difficulty: 5, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 33, xp: 385 },
{name: 'hell raiser', payout: 855, reward: 'firewall', difficulty: 10, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 173, xp: 630 },
{name: 'purple donkey', payout: 546, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 120, xp: 900 },
{name: 'jaba', payout: 913, reward: 'zero_day', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 80, xp: 480 },
{name: 'caboose', payout: 841, reward: 'firewall', difficulty: 8, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 131, xp: 376 },
{name: 'hurricane', payout: 797, reward: 'honeypot', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 155, xp: 150 },
{name: 'quarantine', payout: 1444, reward: 'none', difficulty: 4, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 88, xp: 372 },
{name: 'blowback', payout: 1171, reward: 'none', difficulty: 11, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 51, xp: 847 },
{name: 'hackathon', payout: 812, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 60, xp: 12 },
{name: 'goat cheese', payout: 1509, reward: 'firewall', difficulty: 12, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 108, xp: 648 },
{name: 'caboose', payout: 390, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 59, xp: 54 },
{name: 'typhoon', payout: 1699, reward: 'firewall', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 109, xp: 50 },
{name: 'little boy', payout: 653, reward: 'firewall', difficulty: 6, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 102, xp: 24 },
{name: 'embedded', payout: 1431, reward: 'firewall', difficulty: 6, description: 'Aid LEO search for subject.', time_to_complete: 80, xp: 228 },
{name: 'jam out clam out', payout: 1732, reward: 'firewall', difficulty: 10, description: 'Deter future breaches.  Property retrieval secondary priority.', time_to_complete: 175, xp: 860 },
{name: 'baboon', payout: 1229, reward: 'none', difficulty: 11, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 165, xp: 880 },
{name: 'bern-inator', payout: 1001, reward: 'firewall', difficulty: 2, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 120, xp: 134 },
{name: 'jaba', payout: 1465, reward: 'o_contract', difficulty: 3, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 136, xp: 183 },
{name: 'top gun', payout: 443, reward: 'none', difficulty: 5, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 85, xp: 200 },
{name: 'backdraft', payout: 1139, reward: 'firewall', difficulty: 7, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 57, xp: 294 },
{name: 'turtle', payout: 246, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 40, xp: 24 },
{name: 'half a beer', payout: 552, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 88, xp: 1000 },
{name: 'turtle', payout: 837, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 128, xp: 59 },
{name: 'coldcuts', payout: 317, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 117, xp: 370 },
{name: 'vigo', payout: 1861, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 176, xp: 456 },
{name: 'turtle', payout: 133, reward: 'none', difficulty: 1, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 105, xp: 59 },
{name: 'quarantine', payout: 1792, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 78, xp: 104 },
{name: 'thunder****', payout: 1647, reward: 'firewall', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 169, xp: 120 },
{name: 'bannana? bannanna?', payout: 1850, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 40, xp: 504 },
{name: 'hackathon', payout: 785, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 167, xp: 238 },
{name: 'thunder****', payout: 183, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 89, xp: 637 },
{name: 'turkey', payout: 1924, reward: 'none', difficulty: 1, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 31, xp: 67 },
{name: 'whateverthefuck', payout: 827, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 95, xp: 315 },
{name: 'juicy', payout: 825, reward: 'firewall', difficulty: 5, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 163, xp: 315 },
{name: 'fat man', payout: 1823, reward: 'firewall', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 162, xp: 495 },
{name: 'hardball', payout: 541, reward: 'none', difficulty: 7, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 99, xp: 140 },
{name: 'goat cheese', payout: 1382, reward: 'none', difficulty: 4, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 31, xp: 232 },
{name: 'hackathon', payout: 0, reward: 'firewall', difficulty: 5, description: 'Aid Japanese LEO in recovery of trafficking victims.', time_to_complete: 123, xp: 335 },
{name: 'taco', payout: 1955, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 124, xp: 165 },
{name: 'brown nose', payout: 1220, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 104, xp: 132 },
{name: 'false idol', payout: 1893, reward: 'zero_day', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 88, xp: 14 },
{name: 'purple donkey', payout: 1393, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of personell before estimated border crossing.', time_to_complete: 94, xp: 810 },
{name: 'anvil', payout: 995, reward: 'none', difficulty: 2, description: 'Suspects in theft confirmed.  Locate and subdue.  Data integrity is priority one.', time_to_complete: 160, xp: 92 },
{name: 'recovery', payout: 74, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 93, xp: 581 },
{name: 'consumnes', payout: 84, reward: 'firewall', difficulty: 1, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 80, xp: 19 },
{name: 'top gun', payout: 1545, reward: 'firewall', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 58, xp: 57 },
{name: 'hellraiser', payout: 794, reward: 'none', difficulty: 4, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 56, xp: 244 },
{name: 'quarantine', payout: 1396, reward: 'firewall', difficulty: 6, description: 'Deter future breaches on --REDACTED-- by destroying all stolen assets. Civilian casualties will reduce bonus.', time_to_complete: 118, xp: 258 },
{name: 'salamander', payout: 1222, reward: 'none', difficulty: 12, description: 'VIP kidnapping in progress. --REDACTED-- has insurance on VIP, no negotiations.', time_to_complete: 163, xp: 708 },
{name: 'quarantine', payout: 260, reward: 'firewall', difficulty: 12, description: 'VIP kidnapping in progress. Seek/destroy after VIP extract.', time_to_complete: 131, xp: 300 },
{name: 'hackathon', payout: 1014, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 144, xp: 420 },
{name: 'applesauce', payout: 576, reward: 'firewall', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 48, xp: 9 },
{name: 'top gun', payout: 178, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 78, xp: 264 },
{name: 'second coming', payout: 1702, reward: 'firewall', difficulty: 2, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 67, xp: 124 },
{name: 'wtf', payout: 1512, reward: 'none', difficulty: 11, description: 'Aid Canadian LEO in recovery of assets.', time_to_complete: 48, xp: 924 },
{name: 'bluejay', payout: 1803, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 46, xp: 91 },
{name: 'trump-inator', payout: 1011, reward: 'firewall', difficulty: 6, description: 'After a mega-breach a company needs data retrieval.  Heavy resistance expected.', time_to_complete: 139, xp: 420 },
{name: 'baboon', payout: 242, reward: 'none', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 82, xp: 350 },
{name: 'snake eater', payout: 1257, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 104, xp: 121 },
{name: 'victor', payout: 1759, reward: 'zero_day', difficulty: 1, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 97, xp: 40 },
{name: 'embedded', payout: 793, reward: 'none', difficulty: 3, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 148, xp: 297 },
{name: 'applesauce', payout: 1532, reward: 'firewall', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 50, xp: 820 },
{name: 'victor', payout: 1441, reward: 'firewall', difficulty: 1, description: 'VIP blackmail suspects located. VIP has gave no constraints. Seek/destroy.', time_to_complete: 61, xp: 83 },
{name: 'gale', payout: 1551, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 132, xp: 198 }
]
    )
