# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

t = Time.now + 3

users = User.create(
  [
    { name: 'alice', password: 'a', firewall: 5, honeypot: 2, zeroday: 5, o_contract: 1 },    
    { name: 'bob', password: 'b', firewall: 2, honeypot: 2, active_firewall: 5, active_honeypot: 3 },    
    { name: 'charlie', password: 'c' },    
    { name: 'david', password: 'd' }    
  ]
)

breaches = Breach.create(
  [
    #alice is targeting bob OR bob is targeted by alice
    {user_id: 1, target_id: 2, breached: false},
    {user_id: 1, target_id: 3, breached: true, cash_stolen: 1000},
    {user_id: 1, target_id: 2, breached: false},

    {user_id: 2, target_id: 1, breached: false},
    {user_id: 2, target_id: 4, breached: false},

    {user_id: 3, target_id: 1, breached: false},

    {user_id: 4, target_id: 1, breached: false},
    {user_id: 4, target_id: 2, breached: false}
  ]
)

operatives = Operative.create(
  [
    { user_id: 1, name: 'Smiling Gibbon', status: 'deployed', skill: 7, job_id: 1 },
    { user_id: 1, name: 'Sitting Tofu', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Fuze', status: 'injured', skill: 4, job_id: nil },
    { user_id: 1, name: 'Black Swan', status: 'mia', skill: 3, job_id: nil },

    { user_id: 2, name: 'Daft Adder', status: 'injured', skill: 6, job_id: nil },
    { user_id: 2, name: 'Stale Hammer', status: 'deployed', skill: 2, job_id: nil },
    { user_id: 2, name: 'Orange Rocket', status: 'deployed', skill: 3, job_id: nil },
    { user_id: 2, name: 'Steel Sun', status: 'deployed', skill: 4, job_id: nil },

    { user_id: 4, name: 'Yoga', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Cunning Turtle', status: 'deployed', skill: 1, job_id: nil },
    { user_id: 4, name: 'Gypsy', status: 'dead', skill: 4, job_id: nil },
    { user_id: 4, name: 'Alpha', status: 'mia', skill: 8, job_id: nil }

  ]
)


jobs = Job.create(
    [
{name: 'papa', payout: 1159, reward: 'o_contract', difficulty: 3, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 49, xp: 105 },
{name: 'firesail', payout: 563, reward: 'honeypot', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 145, xp: 594 },
{name: 'gale', payout: 1719, reward: 'none', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 99, xp: 324 },
{name: 'recovery', payout: 609, reward: 'none', difficulty: 2, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 121, xp: 144 },
{name: 'breach', payout: 932, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 139, xp: 24 },
{name: 'moose', payout: 442, reward: 'zero_day', difficulty: 10, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 105, xp: 410 },
{name: 'bannana? bannanna?', payout: 1587, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 177, xp: 528 },
{name: 'backdraft', payout: 1160, reward: 'honeypot', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 54, xp: 440 },
{name: 'half a beer', payout: 1966, reward: 'none', difficulty: 8, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 178, xp: 592 },
{name: 'backdraft', payout: 213, reward: 'firewall', difficulty: 12, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 155, xp: 552 },
{name: 'quarantine', payout: 434, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 50, xp: 39 },
{name: 'thunder****', payout: 1790, reward: 'o_contract', difficulty: 9, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 143, xp: 621 },
{name: 'hell raiser', payout: 837, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 65, xp: 265 },
{name: 'thunder****', payout: 539, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 134, xp: 246 },
{name: 'thunder****', payout: 1472, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 31, xp: 48 },
{name: 'bluejay', payout: 1784, reward: 'zero_day', difficulty: 3, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 101, xp: 66 },
{name: 'embedded', payout: 546, reward: 'firewall', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 134, xp: 715 },
{name: 'cheney', payout: 115, reward: 'none', difficulty: 3, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 94, xp: 144 },
{name: 'black eye', payout: 956, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 113, xp: 72 },
{name: 'black hawk', payout: 534, reward: 'firewall', difficulty: 6, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 76, xp: 330 },
{name: 'bern-inator', payout: 498, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 55, xp: 0 },
{name: 'papa', payout: 1067, reward: 'none', difficulty: 1, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 169, xp: 27 },
{name: 'second coming', payout: 315, reward: 'none', difficulty: 8, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 177, xp: 8 },
{name: 'bannana? bannanna?', payout: 877, reward: 'firewall', difficulty: 1, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 170, xp: 21 },
{name: 'fang', payout: 1967, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 170, xp: 78 },
{name: 'anvil', payout: 1168, reward: 'firewall', difficulty: 3, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 40, xp: 192 },
{name: 'alpha', payout: 1514, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 66, xp: 800 },
{name: 'typhoon', payout: 98, reward: 'none', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 107, xp: 336 },
{name: 'papa', payout: 837, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 175, xp: 135 },
{name: 'quarantine', payout: 1495, reward: 'none', difficulty: 9, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 115, xp: 774 },
{name: 'blowback', payout: 1897, reward: 'zero_day', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 163, xp: 468 },
{name: 'papa', payout: 1196, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 98, xp: 70 },
{name: 'black eye', payout: 981, reward: 'none', difficulty: 7, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 165, xp: 581 },
{name: 'victor', payout: 595, reward: 'o_contract', difficulty: 7, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 53, xp: 49 },
{name: 'wtf', payout: 1518, reward: 'firewall', difficulty: 1, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 108, xp: 5 },
{name: 'gibbon', payout: 1676, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 31, xp: 462 },
{name: 'bravo', payout: 713, reward: 'firewall', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 179, xp: 600 },
{name: 'typhoon', payout: 1701, reward: 'none', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 177, xp: 240 },
{name: 'applesauce', payout: 1092, reward: 'none', difficulty: 7, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 39, xp: 266 },
{name: 'smokescreen', payout: 1560, reward: 'zero_day', difficulty: 5, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 91, xp: 20 },
{name: 'fang', payout: 826, reward: 'honeypot', difficulty: 10, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 110, xp: 520 },
{name: 'hurricane', payout: 653, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 47, xp: 576 },
{name: 'wtf', payout: 941, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 109, xp: 120 },
{name: 'brown nose', payout: 93, reward: 'firewall', difficulty: 8, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 162, xp: 344 },
{name: 'hurricane', payout: 660, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 59, xp: 873 },
{name: 'hardball', payout: 351, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 179, xp: 979 },
{name: 'whateverthefuck', payout: 913, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 88, xp: 90 },
{name: 'applesauce', payout: 1733, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 110, xp: 80 },
{name: 'bravo', payout: 1720, reward: 'firewall', difficulty: 8, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 110, xp: 504 },
{name: 'vigo', payout: 1483, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 81, xp: 38 },
{name: 'muffintop', payout: 61, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 83, xp: 426 },
{name: 'blowback', payout: 1871, reward: 'honeypot', difficulty: 12, description: 'Aid LEO search for subject.', time_to_complete: 83, xp: 876 },
{name: 'moose', payout: 507, reward: 'none', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 84, xp: 510 },
{name: 'gale', payout: 49, reward: 'none', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 35, xp: 138 },
{name: 'purple donkey', payout: 1720, reward: 'none', difficulty: 9, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 81, xp: 801 },
{name: 'typhoon', payout: 943, reward: 'none', difficulty: 6, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 151, xp: 444 },
{name: 'jam out clam out', payout: 1517, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 167, xp: 160 },
{name: 'half a beer', payout: 954, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 105, xp: 95 },
{name: 'recovery', payout: 1235, reward: 'firewall', difficulty: 1, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 171, xp: 10 },
{name: 'dustoff', payout: 1915, reward: 'o_contract', difficulty: 3, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 180, xp: 273 },
{name: 'fang', payout: 226, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 39, xp: 585 },
{name: 'dustoff', payout: 647, reward: 'none', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 80, xp: 50 },
{name: 'hurricane', payout: 1729, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 37, xp: 156 },
{name: 'iron eagle', payout: 1909, reward: 'firewall', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 110, xp: 180 },
{name: 'shutdown', payout: 823, reward: 'none', difficulty: 7, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 59, xp: 126 },
{name: 'black hawk', payout: 409, reward: 'firewall', difficulty: 8, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 159, xp: 592 },
{name: 'alpha', payout: 1100, reward: 'firewall', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 112, xp: 330 },
{name: 'backdraft', payout: 999, reward: 'none', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 96, xp: 8 },
{name: 'breach', payout: 1596, reward: 'firewall', difficulty: 10, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 155, xp: 370 },
{name: 'fang', payout: 323, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 115, xp: 200 },
{name: 'salamander', payout: 1201, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 89, xp: 280 },
{name: 'whateverthefuck', payout: 1061, reward: 'firewall', difficulty: 12, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 110, xp: 600 },
{name: 'juicy', payout: 1095, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 88, xp: 190 },
{name: 'hellraiser', payout: 1061, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 55, xp: 448 },
{name: 'black eye', payout: 1334, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 129, xp: 792 },
{name: 'purple donkey', payout: 1526, reward: 'zero_day', difficulty: 7, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 83, xp: 511 },
{name: 'snake eater', payout: 1133, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 165, xp: 803 },
{name: 'hellraiser', payout: 1981, reward: 'firewall', difficulty: 12, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 34, xp: 696 },
{name: 'taco', payout: 217, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 119, xp: 86 },
{name: 'blacksmith', payout: 899, reward: 'none', difficulty: 4, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 154, xp: 264 },
{name: 'top gun', payout: 105, reward: 'o_contract', difficulty: 6, description: 'Aid LEO search for subject.', time_to_complete: 83, xp: 354 },
{name: 'juicy', payout: 1914, reward: 'firewall', difficulty: 10, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 161, xp: 860 },
{name: 'top gun', payout: 557, reward: 'firewall', difficulty: 2, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 74, xp: 88 },
{name: 'consumnes', payout: 1180, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 161, xp: 148 },
{name: 'jam out clam out', payout: 844, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 96, xp: 282 },
{name: 'richard', payout: 481, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 162, xp: 474 },
{name: 'jaba', payout: 1520, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 170, xp: 30 },
{name: 'black hawk', payout: 1742, reward: 'o_contract', difficulty: 6, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 139, xp: 456 },
{name: 'quarantine', payout: 1983, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 158, xp: 166 },
{name: 'bannana? bannanna?', payout: 623, reward: 'firewall', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 165, xp: 380 },
{name: 'anvil', payout: 1925, reward: 'none', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 137, xp: 150 },
{name: 'chico', payout: 951, reward: 'none', difficulty: 5, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 179, xp: 360 },
{name: 'black hawk', payout: 1980, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 176, xp: 180 },
{name: 'caboose', payout: 1745, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 38, xp: 72 },
{name: 'gale', payout: 1068, reward: 'firewall', difficulty: 8, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 166, xp: 24 },
{name: 'typhoon', payout: 1573, reward: 'firewall', difficulty: 9, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 142, xp: 819 },
{name: 'typhoon', payout: 916, reward: 'honeypot', difficulty: 2, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 148, xp: 192 },
{name: 'alpha', payout: 229, reward: 'firewall', difficulty: 11, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 141, xp: 1034 },
{name: 'hell raiser', payout: 137, reward: 'none', difficulty: 3, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 177, xp: 54 },
{name: 'gale', payout: 268, reward: 'firewall', difficulty: 9, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 175, xp: 189 },
{name: 'backdraft', payout: 1367, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 153, xp: 252 },
{name: 'caboose', payout: 375, reward: 'zero_day', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 86, xp: 207 },
{name: 'alpha', payout: 1992, reward: 'zero_day', difficulty: 10, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 64, xp: 200 },
{name: 'victor', payout: 360, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 163, xp: 16 },
{name: 'hackathon', payout: 479, reward: 'none', difficulty: 3, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 104, xp: 132 },
{name: 'little boy', payout: 646, reward: 'none', difficulty: 7, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 40, xp: 665 },
{name: 'gale', payout: 778, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 46, xp: 78 },
{name: 'typhoon', payout: 462, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 105, xp: 148 },
{name: 'backdraft', payout: 1674, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 179, xp: 488 },
{name: 'thunder****', payout: 1227, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 110, xp: 44 },
{name: 'bluejay', payout: 587, reward: 'firewall', difficulty: 3, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 59, xp: 141 },
{name: 'consumnes', payout: 996, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 169, xp: 36 },
{name: 'caboose', payout: 1993, reward: 'zero_day', difficulty: 2, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 135, xp: 46 },
{name: 'f.o.b.', payout: 1794, reward: 'firewall', difficulty: 6, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 65, xp: 318 },
{name: 'chico', payout: 709, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 148, xp: 180 },
{name: 'moose', payout: 1695, reward: 'none', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 157, xp: 8 },
{name: 'chico', payout: 1733, reward: 'none', difficulty: 7, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 113, xp: 434 },
{name: 'juicy', payout: 957, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 62, xp: 273 },
{name: 'wtf', payout: 1734, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 80, xp: 704 },
{name: 'bern-inator', payout: 517, reward: 'none', difficulty: 1, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 46, xp: 27 },
{name: 'blowback', payout: 1198, reward: 'zero_day', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 56, xp: 759 },
{name: 'shutdown', payout: 1430, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 168, xp: 5 },
{name: 'papa', payout: 1397, reward: 'firewall', difficulty: 4, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 71, xp: 44 },
{name: 'alpha', payout: 1793, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 180, xp: 161 },
{name: 'consumnes', payout: 787, reward: 'honeypot', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 88, xp: 341 },
{name: 'breach', payout: 1566, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 156, xp: 33 },
{name: 'firesail', payout: 718, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 180, xp: 616 },
{name: 'richard', payout: 1343, reward: 'honeypot', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 33, xp: 15 },
{name: 'bannana? bannanna?', payout: 1832, reward: 'none', difficulty: 2, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 176, xp: 154 },
{name: 'purple donkey', payout: 1169, reward: 'firewall', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 161, xp: 630 },
{name: 'turtle', payout: 1698, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 162, xp: 574 },
{name: 'baboon', payout: 1522, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 170, xp: 649 },
{name: 'gale', payout: 1826, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 164, xp: 276 },
{name: 'caboose', payout: 1905, reward: 'firewall', difficulty: 11, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 178, xp: 77 },
{name: 'wtf', payout: 1418, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 34, xp: 21 },
{name: 'jam out clam out', payout: 645, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 114, xp: 72 },
{name: 'wtf', payout: 328, reward: 'firewall', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 78, xp: 396 },
{name: 'quarantine', payout: 1353, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 138, xp: 584 },
{name: 'typhoon', payout: 92, reward: 'zero_day', difficulty: 7, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 30, xp: 112 },
{name: 'purple donkey', payout: 765, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 44, xp: 4 },
{name: 'sherpa', payout: 519, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 66, xp: 74 },
{name: 'vigo', payout: 341, reward: 'firewall', difficulty: 11, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 95, xp: 429 },
{name: 'turtle', payout: 106, reward: 'o_contract', difficulty: 5, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 84, xp: 110 },
{name: 'tango', payout: 442, reward: 'o_contract', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 87, xp: 680 },
{name: 'purple donkey', payout: 1018, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 162, xp: 114 },
{name: 'wtf', payout: 1301, reward: 'none', difficulty: 8, description: 'Aid LEO search for subject.', time_to_complete: 75, xp: 448 },
{name: 'black hawk', payout: 156, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 132, xp: 296 },
{name: 'bluejay', payout: 729, reward: 'none', difficulty: 10, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 156, xp: 510 },
{name: 'anvil', payout: 1540, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 109, xp: 171 },
{name: 'bannana? bannanna?', payout: 400, reward: 'firewall', difficulty: 10, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 46, xp: 770 },
{name: 'bluejay', payout: 429, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 107, xp: 946 },
{name: 'chico', payout: 349, reward: 'firewall', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 77, xp: 142 },
{name: 'dustoff', payout: 331, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 121, xp: 288 },
{name: 'trump-inator', payout: 1395, reward: 'firewall', difficulty: 1, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 52, xp: 77 },
{name: 'hardball', payout: 390, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 51, xp: 261 },
{name: 'firesail', payout: 611, reward: 'honeypot', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 50, xp: 603 },
{name: 'turkey', payout: 74, reward: 'firewall', difficulty: 5, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 88, xp: 470 },
{name: 'firesail', payout: 1421, reward: 'none', difficulty: 4, description: 'Aid LEO search for subject.', time_to_complete: 123, xp: 132 },
{name: 'top gun', payout: 1144, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 106, xp: 48 },
{name: 'false idol', payout: 436, reward: 'firewall', difficulty: 7, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 50, xp: 294 },
{name: 'bannana? bannanna?', payout: 959, reward: 'firewall', difficulty: 11, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 132, xp: 143 },
{name: 'embedded', payout: 1971, reward: 'o_contract', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 144, xp: 231 },
{name: 'typhoon', payout: 982, reward: 'none', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 102, xp: 960 },
{name: 'blowback', payout: 544, reward: 'none', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 84, xp: 354 },
{name: 'muffintop', payout: 581, reward: 'zero_day', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 119, xp: 245 },
{name: 'goat cheese', payout: 40, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 55, xp: 20 },
{name: 'jaba', payout: 816, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 121, xp: 882 },
{name: 'jam out clam out', payout: 773, reward: 'firewall', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 149, xp: 369 },
{name: 'brown nose', payout: 58, reward: 'firewall', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 175, xp: 9 },
{name: 'goat cheese', payout: 219, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 122, xp: 91 },
{name: 'hackathon', payout: 252, reward: 'firewall', difficulty: 11, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 125, xp: 352 },
{name: 'recovery', payout: 1562, reward: 'firewall', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 114, xp: 126 },
{name: 'jam out clam out', payout: 1176, reward: 'zero_day', difficulty: 1, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 133, xp: 63 },
{name: 'goat cheese', payout: 1163, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 31, xp: 24 },
{name: 'chico', payout: 814, reward: 'none', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 178, xp: 328 },
{name: 'consumnes', payout: 1868, reward: 'none', difficulty: 3, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 80, xp: 201 },
{name: 'purple donkey', payout: 1653, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 104, xp: 356 },
{name: 'firesail', payout: 1094, reward: 'firewall', difficulty: 5, description: 'Aid LEO search for subject.', time_to_complete: 30, xp: 120 },
{name: 'juicy', payout: 111, reward: 'firewall', difficulty: 4, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 136, xp: 136 },
{name: 'second coming', payout: 1217, reward: 'none', difficulty: 7, description: 'Aid LEO search for subject.', time_to_complete: 157, xp: 252 },
{name: 'firesail', payout: 1103, reward: 'none', difficulty: 10, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 154, xp: 40 },
{name: 'goat cheese', payout: 86, reward: 'o_contract', difficulty: 3, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 163, xp: 117 },
{name: 'hell raiser', payout: 1733, reward: 'o_contract', difficulty: 11, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 163, xp: 330 },
{name: 'bern-inator', payout: 145, reward: 'honeypot', difficulty: 9, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 152, xp: 648 },
{name: 'embedded', payout: 991, reward: 'none', difficulty: 1, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 65, xp: 87 },
{name: 'dustoff', payout: 1587, reward: 'none', difficulty: 5, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 89, xp: 300 },
{name: 'typhoon', payout: 1649, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 46, xp: 90 },
{name: 'firesail', payout: 1027, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 112, xp: 3 },
{name: 'hardball', payout: 1287, reward: 'none', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 76, xp: 36 },
{name: 'jam out clam out', payout: 1656, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 157, xp: 400 },
{name: 'caboose', payout: 1488, reward: 'honeypot', difficulty: 5, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 59, xp: 95 },
{name: 'trump-inator', payout: 263, reward: 'firewall', difficulty: 6, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 67, xp: 240 },
{name: 'black hawk', payout: 1747, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 63, xp: 1104 },
{name: 'little boy', payout: 314, reward: 'firewall', difficulty: 12, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 35, xp: 420 },
{name: 'recovery', payout: 794, reward: 'firewall', difficulty: 1, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 76, xp: 35 },
{name: 'applesauce', payout: 683, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 109, xp: 576 },
{name: 'embedded', payout: 660, reward: 'none', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 82, xp: 0 },
{name: 'gibbon', payout: 1864, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 42, xp: 216 },
{name: 'alpha', payout: 1472, reward: 'none', difficulty: 12, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 157, xp: 1176 },
{name: 'turkey', payout: 113, reward: 'none', difficulty: 6, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 34, xp: 192 },
{name: 'taco', payout: 1275, reward: 'o_contract', difficulty: 8, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 106, xp: 720 },
{name: 'consumnes', payout: 1972, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 179, xp: 348 },
{name: 'blacksmith', payout: 1435, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 160, xp: 513 },
{name: 'dustoff', payout: 1381, reward: 'firewall', difficulty: 10, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 58, xp: 720 },
{name: 'tango', payout: 155, reward: 'firewall', difficulty: 8, description: 'Aid LEO search for subject.', time_to_complete: 46, xp: 272 },
{name: 'thunder****', payout: 730, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 124, xp: 120 },
{name: 'snake eater', payout: 783, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 117, xp: 20 },
{name: 'backdraft', payout: 35, reward: 'firewall', difficulty: 10, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 176, xp: 650 },
{name: 'sherpa', payout: 489, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 164, xp: 144 },
{name: 'consumnes', payout: 1145, reward: 'o_contract', difficulty: 6, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 58, xp: 156 },
{name: 'embedded', payout: 53, reward: 'firewall', difficulty: 4, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 107, xp: 92 },
{name: 'bannana? bannanna?', payout: 909, reward: 'firewall', difficulty: 1, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 127, xp: 33 },
{name: 'thunder****', payout: 1126, reward: 'none', difficulty: 10, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 128, xp: 950 },
{name: 'breach', payout: 1800, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 157, xp: 105 },
{name: 'brown nose', payout: 1713, reward: 'firewall', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 151, xp: 372 },
{name: 'breach', payout: 567, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 177, xp: 287 },
{name: 'chico', payout: 585, reward: 'firewall', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 67, xp: 60 },
{name: 'second coming', payout: 1712, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 154, xp: 216 },
{name: 'black hawk', payout: 1056, reward: 'none', difficulty: 12, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 131, xp: 588 },
{name: 'embedded', payout: 1021, reward: 'firewall', difficulty: 11, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 32, xp: 286 },
{name: 'recovery', payout: 648, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 32, xp: 147 },
{name: 'false idol', payout: 642, reward: 'firewall', difficulty: 2, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 113, xp: 166 },
{name: 'coldcuts', payout: 1961, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 64, xp: 30 },
{name: 'f.o.b.', payout: 1536, reward: 'o_contract', difficulty: 6, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 180, xp: 216 },
{name: 'wtf', payout: 1461, reward: 'none', difficulty: 12, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 74, xp: 792 },
{name: 'firesail', payout: 143, reward: 'none', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 56, xp: 166 },
{name: 'half a beer', payout: 1785, reward: 'none', difficulty: 10, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 36, xp: 760 },
{name: 'shutdown', payout: 1842, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 93, xp: 296 },
{name: 'recovery', payout: 912, reward: 'o_contract', difficulty: 1, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 167, xp: 34 },
{name: 'caboose', payout: 1557, reward: 'o_contract', difficulty: 1, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 150, xp: 97 },
{name: 'breach', payout: 1475, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 123, xp: 40 },
{name: 'breach', payout: 998, reward: 'firewall', difficulty: 9, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 66, xp: 432 },
{name: 'iron eagle', payout: 179, reward: 'firewall', difficulty: 8, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 99, xp: 120 },
{name: 'caboose', payout: 1594, reward: 'none', difficulty: 10, description: 'Aid LEO search for subject.', time_to_complete: 94, xp: 490 },
{name: 'gale', payout: 196, reward: 'zero_day', difficulty: 11, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 72, xp: 198 },
{name: 'bluejay', payout: 39, reward: 'none', difficulty: 9, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 65, xp: 306 },
{name: 'whateverthefuck', payout: 1981, reward: 'o_contract', difficulty: 8, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 131, xp: 752 },
{name: 'sherpa', payout: 987, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 114, xp: 801 },
{name: 'whateverthefuck', payout: 345, reward: 'zero_day', difficulty: 8, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 152, xp: 368 },
{name: 'false idol', payout: 1674, reward: 'none', difficulty: 8, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 87, xp: 696 },
{name: 'bluejay', payout: 253, reward: 'firewall', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 115, xp: 306 },
{name: 'coldcuts', payout: 7, reward: 'none', difficulty: 6, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 30, xp: 42 },
{name: 'top gun', payout: 1952, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 157, xp: 774 },
{name: 'hardball', payout: 1326, reward: 'honeypot', difficulty: 10, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 165, xp: 810 },
{name: 'jaba', payout: 386, reward: 'none', difficulty: 3, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 106, xp: 129 },
{name: 'cheney', payout: 661, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 79, xp: 285 },
{name: 'hell raiser', payout: 870, reward: 'firewall', difficulty: 10, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 63, xp: 530 },
{name: 'muffintop', payout: 978, reward: 'firewall', difficulty: 4, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 142, xp: 236 },
{name: 'chico', payout: 1697, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 169, xp: 20 },
{name: 'firesail', payout: 976, reward: 'honeypot', difficulty: 1, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 68, xp: 3 },
{name: 'top gun', payout: 817, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 154, xp: 20 },
{name: 'cheney', payout: 1274, reward: 'none', difficulty: 3, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 106, xp: 12 },
{name: 'vigo', payout: 1411, reward: 'firewall', difficulty: 3, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 180, xp: 282 },
{name: 'baboon', payout: 36, reward: 'honeypot', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 30, xp: 315 },
{name: 'goat cheese', payout: 906, reward: 'none', difficulty: 8, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 97, xp: 400 },
{name: 'black hawk', payout: 314, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 49, xp: 99 },
{name: 'anvil', payout: 276, reward: 'firewall', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 136, xp: 1092 },
{name: 'false idol', payout: 65, reward: 'firewall', difficulty: 1, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 74, xp: 75 },
{name: 'black hawk', payout: 1519, reward: 'firewall', difficulty: 9, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 127, xp: 459 },
{name: 'hackathon', payout: 390, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 46, xp: 549 },
{name: 'hurricane', payout: 1791, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 120, xp: 582 },
{name: 'iron eagle', payout: 124, reward: 'firewall', difficulty: 4, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 80, xp: 120 },
{name: 'bannana? bannanna?', payout: 434, reward: 'none', difficulty: 3, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 139, xp: 159 },
{name: 'quarantine', payout: 451, reward: 'none', difficulty: 11, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 105, xp: 924 },
{name: 'little boy', payout: 1216, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 51, xp: 456 },
{name: 'embedded', payout: 1098, reward: 'none', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 174, xp: 640 },
{name: 'second coming', payout: 857, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 159, xp: 370 },
{name: 'alpha', payout: 1453, reward: 'none', difficulty: 8, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 120, xp: 176 },
{name: 'embedded', payout: 360, reward: 'none', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 60, xp: 152 },
{name: 'wtf', payout: 643, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 171, xp: 540 },
{name: 'papa', payout: 1212, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 49, xp: 567 },
{name: 'gibbon', payout: 1400, reward: 'honeypot', difficulty: 2, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 87, xp: 164 },
{name: 'bluejay', payout: 343, reward: 'firewall', difficulty: 12, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 101, xp: 48 },
{name: 'backdraft', payout: 422, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 132, xp: 990 },
{name: 'dustoff', payout: 1776, reward: 'zero_day', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 51, xp: 630 },
{name: 'shutdown', payout: 818, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 143, xp: 132 },
{name: 'f.o.b.', payout: 1197, reward: 'firewall', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 142, xp: 160 },
{name: 'juicy', payout: 605, reward: 'none', difficulty: 8, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 122, xp: 584 },
{name: 'gibbon', payout: 132, reward: 'firewall', difficulty: 6, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 98, xp: 384 },
{name: 'gale', payout: 1078, reward: 'none', difficulty: 12, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 94, xp: 600 },
{name: 'breach', payout: 633, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 58, xp: 693 },
{name: 'little boy', payout: 1580, reward: 'firewall', difficulty: 12, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 84, xp: 864 },
{name: 'hardball', payout: 1768, reward: 'none', difficulty: 12, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 82, xp: 1140 },
{name: 'gibbon', payout: 1638, reward: 'o_contract', difficulty: 10, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 53, xp: 90 },
{name: 'baboon', payout: 998, reward: 'firewall', difficulty: 5, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 140, xp: 175 },
{name: 'typhoon', payout: 317, reward: 'firewall', difficulty: 12, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 170, xp: 1140 },
{name: 'brown nose', payout: 454, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 56, xp: 96 },
{name: 'anvil', payout: 1152, reward: 'none', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 132, xp: 372 },
{name: 'bern-inator', payout: 1801, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 55, xp: 82 },
{name: 'taco', payout: 241, reward: 'none', difficulty: 7, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 167, xp: 182 },
{name: 'bluejay', payout: 567, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 150, xp: 495 },
{name: 'shutdown', payout: 1758, reward: 'firewall', difficulty: 9, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 81, xp: 360 },
{name: 'bannana? bannanna?', payout: 1880, reward: 'firewall', difficulty: 1, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 156, xp: 58 },
{name: 'false idol', payout: 1110, reward: 'o_contract', difficulty: 1, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 47, xp: 50 },
{name: 'jam out clam out', payout: 514, reward: 'none', difficulty: 5, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 77, xp: 100 },
{name: 'gale', payout: 1383, reward: 'firewall', difficulty: 9, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 118, xp: 180 },
{name: 'iron eagle', payout: 835, reward: 'firewall', difficulty: 4, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 78, xp: 112 },
{name: 'alpha', payout: 881, reward: 'firewall', difficulty: 9, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 70, xp: 531 },
{name: 'f.o.b.', payout: 1904, reward: 'none', difficulty: 11, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 80, xp: 550 },
{name: 'salamander', payout: 810, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 159, xp: 360 },
{name: 'hurricane', payout: 1052, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 149, xp: 690 },
{name: 'juicy', payout: 1442, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 139, xp: 162 },
{name: 'iron eagle', payout: 1299, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 168, xp: 95 },
{name: 'muffintop', payout: 285, reward: 'firewall', difficulty: 1, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 128, xp: 55 },
{name: 'typhoon', payout: 758, reward: 'o_contract', difficulty: 5, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 123, xp: 300 },
{name: 'richard', payout: 110, reward: 'honeypot', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 147, xp: 90 },
{name: 'trump-inator', payout: 146, reward: 'none', difficulty: 3, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 91, xp: 300 },
{name: 'brown nose', payout: 1405, reward: 'none', difficulty: 10, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 76, xp: 190 },
{name: 'quarantine', payout: 237, reward: 'honeypot', difficulty: 4, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 94, xp: 284 },
{name: 'juicy', payout: 157, reward: 'none', difficulty: 3, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 56, xp: 99 },
{name: 'goat cheese', payout: 208, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 74, xp: 59 },
{name: 'second coming', payout: 935, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 63, xp: 174 },
{name: 'bravo', payout: 811, reward: 'none', difficulty: 2, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 114, xp: 150 },
{name: 'muffintop', payout: 1888, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 63, xp: 39 },
{name: 'firesail', payout: 173, reward: 'firewall', difficulty: 8, description: 'Aid LEO search for subject.', time_to_complete: 91, xp: 96 },
{name: 'anvil', payout: 498, reward: 'firewall', difficulty: 11, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 165, xp: 462 },
{name: 'alpha', payout: 671, reward: 'none', difficulty: 9, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 147, xp: 531 },
{name: 'victor', payout: 917, reward: 'none', difficulty: 7, description: 'Aid LEO search for subject.', time_to_complete: 82, xp: 518 },
{name: 'hurricane', payout: 979, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 73, xp: 272 },
{name: 'papa', payout: 980, reward: 'none', difficulty: 6, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 107, xp: 498 },
{name: 'tango', payout: 182, reward: 'firewall', difficulty: 5, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 30, xp: 290 },
{name: 'caboose', payout: 173, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 103, xp: 84 },
{name: 'fat man', payout: 1935, reward: 'none', difficulty: 5, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 70, xp: 455 },
{name: 'gale', payout: 1367, reward: 'none', difficulty: 3, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 151, xp: 228 },
{name: 'brown nose', payout: 242, reward: 'firewall', difficulty: 3, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 55, xp: 24 },
{name: 'backdraft', payout: 1417, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 96, xp: 175 },
{name: 'caboose', payout: 1732, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 34, xp: 4 },
{name: 'hurricane', payout: 485, reward: 'firewall', difficulty: 4, description: 'Aid LEO search for subject.', time_to_complete: 101, xp: 248 },
{name: 'jaba', payout: 1925, reward: 'honeypot', difficulty: 5, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 75, xp: 420 },
{name: 'smokescreen', payout: 225, reward: 'firewall', difficulty: 12, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 89, xp: 852 },
{name: 'moose', payout: 759, reward: 'o_contract', difficulty: 6, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 171, xp: 234 },
{name: 'false idol', payout: 1957, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 99, xp: 115 },
{name: 'thunder****', payout: 930, reward: 'none', difficulty: 1, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 161, xp: 87 },
{name: 'black eye', payout: 1952, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 116, xp: 60 },
{name: 'trump-inator', payout: 437, reward: 'firewall', difficulty: 3, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 90, xp: 9 },
{name: 'snake eater', payout: 1737, reward: 'firewall', difficulty: 3, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 87, xp: 108 },
{name: 'jam out clam out', payout: 75, reward: 'none', difficulty: 2, description: 'Aid LEO search for subject.', time_to_complete: 87, xp: 196 },
{name: 'turkey', payout: 596, reward: 'firewall', difficulty: 6, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 51, xp: 270 },
{name: 'typhoon', payout: 1892, reward: 'zero_day', difficulty: 2, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 110, xp: 50 },
{name: 'purple donkey', payout: 1516, reward: 'none', difficulty: 8, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 68, xp: 528 },
{name: 'top gun', payout: 1204, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 34, xp: 418 },
{name: 'black hawk', payout: 861, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 73, xp: 88 },
{name: 'juicy', payout: 187, reward: 'firewall', difficulty: 8, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 155, xp: 424 },
{name: 'typhoon', payout: 1640, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 103, xp: 372 },
{name: 'jam out clam out', payout: 1758, reward: 'honeypot', difficulty: 8, description: 'CODE GREEN on wanted personell in Mid-Atlantic US-China Platform. Wanted ALIVE', time_to_complete: 69, xp: 536 },
{name: 'tango', payout: 701, reward: 'o_contract', difficulty: 10, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 173, xp: 480 },
{name: 'bravo', payout: 1912, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Seattle. Wanted ALIVE --BIOMATTER SENSITIVE--', time_to_complete: 149, xp: 372 },
{name: 'iron eagle', payout: 27, reward: 'firewall', difficulty: 6, description: 'Aid Russian LEO in recovery of data before estimated TTC.', time_to_complete: 81, xp: 24 },
{name: 'quarantine', payout: 1078, reward: 'zero_day', difficulty: 4, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 160, xp: 356 },
{name: 'backdraft', payout: 963, reward: 'none', difficulty: 8, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 113, xp: 768 },
{name: 'iron eagle', payout: 1660, reward: 'none', difficulty: 2, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 178, xp: 190 },
{name: 'hardball', payout: 694, reward: 'o_contract', difficulty: 6, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 88, xp: 246 },
{name: 'fang', payout: 1305, reward: 'zero_day', difficulty: 12, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 91, xp: 528 },
{name: 'iron eagle', payout: 1026, reward: 'none', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 157, xp: 105 },
{name: 'hackathon', payout: 357, reward: 'firewall', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 95, xp: 147 },
{name: 'richard', payout: 161, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 146, xp: 639 },
{name: 'hellraiser', payout: 1079, reward: 'o_contract', difficulty: 2, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 66, xp: 38 },
{name: 'hellraiser', payout: 1832, reward: 'zero_day', difficulty: 10, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 82, xp: 440 },
{name: 'hurricane', payout: 1609, reward: 'zero_day', difficulty: 9, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 125, xp: 468 },
{name: 'moose', payout: 961, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 150, xp: 828 },
{name: 'black hawk', payout: 467, reward: 'o_contract', difficulty: 10, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 117, xp: 200 },
{name: 'gibbon', payout: 97, reward: 'o_contract', difficulty: 2, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 153, xp: 106 },
{name: 'purple donkey', payout: 586, reward: 'zero_day', difficulty: 6, description: 'Aid Chinese LEO in recovery of data before estimated TTC.', time_to_complete: 56, xp: 570 },
{name: 'half a beer', payout: 1419, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  Personnel retrieval secondary priority.', time_to_complete: 176, xp: 396 },
{name: 'jaba', payout: 940, reward: 'none', difficulty: 4, description: 'A recent swingvote by --REDACTED-- board of trustees approved a show of force as retaliaton for corp. espionage.  Prioritize infrastructure.', time_to_complete: 117, xp: 380 },
{name: 'recovery', payout: 1784, reward: 'none', difficulty: 11, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 33, xp: 594 },
{name: 'bluejay', payout: 109, reward: 'firewall', difficulty: 11, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 46, xp: 792 },
{name: 'hellraiser', payout: 936, reward: 'o_contract', difficulty: 11, description: 'Aid US LEO in recovery of data before estimated TTC.', time_to_complete: 129, xp: 451 },
{name: 'richard', payout: 1079, reward: 'firewall', difficulty: 12, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 175, xp: 636 },
{name: 'goat cheese', payout: 1501, reward: 'none', difficulty: 11, description: 'Aid --REDACTED-- in search for market sale of Intellectual Property.', time_to_complete: 54, xp: 154 },
{name: 'hell raiser', payout: 746, reward: 'none', difficulty: 12, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 83, xp: 264 },
{name: 'turtle', payout: 1550, reward: 'firewall', difficulty: 8, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 33, xp: 392 },
{name: 'consumnes', payout: 1568, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 117, xp: 35 },
{name: 'alpha', payout: 488, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted DEAD or ALIVE', time_to_complete: 140, xp: 92 },
{name: 'recovery', payout: 517, reward: 'none', difficulty: 4, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 122, xp: 196 },
{name: 'fang', payout: 1662, reward: 'none', difficulty: 9, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 72, xp: 585 },
{name: 'anvil', payout: 579, reward: 'firewall', difficulty: 5, description: 'CODE GREEN on wanted personell in Prague. Wanted ALIVE', time_to_complete: 93, xp: 485 },
{name: 'breach', payout: 1434, reward: 'firewall', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 135, xp: 486 },
{name: 'blacksmith', payout: 104, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 62, xp: 96 },
{name: 'black hawk', payout: 1702, reward: 'firewall', difficulty: 11, description: 'Aid Canadian LEO in recovery of data before estimated TTC.', time_to_complete: 50, xp: 352 },
{name: 'turtle', payout: 1743, reward: 'zero_day', difficulty: 12, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 160, xp: 1164 },
{name: 'hardball', payout: 1795, reward: 'none', difficulty: 3, description: 'Aid LEO search for subject.', time_to_complete: 146, xp: 246 },
{name: 'firesail', payout: 561, reward: 'honeypot', difficulty: 2, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 72, xp: 64 },
{name: 'dustoff', payout: 50, reward: 'firewall', difficulty: 1, description: 'Deter future breaches via any means necessary.  No Restrictions.', time_to_complete: 160, xp: 28 },
{name: 'iron eagle', payout: 981, reward: 'firewall', difficulty: 8, description: 'CODE GREEN on wanted personell in Uptown Hong Kong. Wanted ALIVE', time_to_complete: 177, xp: 80 },
{name: 'wtf', payout: 1508, reward: 'firewall', difficulty: 10, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 78, xp: 460 },
{name: 'bluejay', payout: 1324, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in RU Launch Pad. DEAD or ALIVE --MUST NOT BREACH ATMO--', time_to_complete: 53, xp: 216 },
{name: 'recovery', payout: 1535, reward: 'none', difficulty: 10, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 84, xp: 440 },
{name: 'salamander', payout: 287, reward: 'none', difficulty: 6, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 112, xp: 246 },
{name: 'chico', payout: 1142, reward: 'firewall', difficulty: 7, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 63, xp: 609 },
{name: 'anvil', payout: 983, reward: 'none', difficulty: 7, description: 'Aid --REDACTED-- in recovery of data before estimated TTC.', time_to_complete: 146, xp: 553 },
{name: 'breach', payout: 1310, reward: 'none', difficulty: 9, description: 'Deter future breaches via any means necessary.  Property retrieval secondary priority.', time_to_complete: 30, xp: 756 },
{name: 'juicy', payout: 1048, reward: 'firewall', difficulty: 12, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 35, xp: 240 },
{name: 'black eye', payout: 1561, reward: 'none', difficulty: 10, description: 'After a mega-breach a company needs data retrieval experts.  Heavy resistance expected.', time_to_complete: 140, xp: 180 },
{name: 'juicy', payout: 1198, reward: 'none', difficulty: 2, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 53, xp: 92 },
{name: 'jam out clam out', payout: 1407, reward: 'firewall', difficulty: 9, description: 'CODE GREEN on wanted personell in Southern Beijing. Wanted ALIVE', time_to_complete: 137, xp: 27 },
{name: 'anvil', payout: 421, reward: 'zero_day', difficulty: 10, description: 'Aid Japanese LEO in recovery of data before estimated TTC.', time_to_complete: 51, xp: 950 },
{name: 'consumnes', payout: 1581, reward: 'zero_day', difficulty: 9, description: 'CODE GREEN on wanted personell in Old District Berlin. Wanted ALIVE', time_to_complete: 105, xp: 558 },
{name: 'little boy', payout: 323, reward: 'firewall', difficulty: 1, description: 'CODE GREEN on wanted personell in Lower Tokyo. Wanted DEAD', time_to_complete: 142, xp: 78 },
{name: 'dustoff', payout: 1824, reward: 'firewall', difficulty: 2, description: 'Deter future breaches via any means necessary.  Data retrieval secondary priority.', time_to_complete: 111, xp: 8 },
{name: 'moose', payout: 152, reward: 'none', difficulty: 3, description: 'CODE GREEN on wanted personell in E. Detroit. DOA Preffered', time_to_complete: 176, xp: 126 }
]
    )
